export type SalesStage={title:string;purpose:string;text:string;tip:string};
export const salesChannels=[{id:'whatsapp',name:'WhatsApp',description:'Conversa direta e acompanhamento'},{id:'instagram',name:'Instagram',description:'Direct e interação com o perfil'},{id:'ligacao',name:'Ligação',description:'Conversa curta e objetiva'},{id:'linkedin',name:'LinkedIn',description:'Decisores e negócios B2B'},{id:'email',name:'E-mail',description:'Prospecção e sequência de respostas'}] as const;
export const salesSituations=[{id:'sem-site',name:'Empresa sem site',angle:'a ausência de um site próprio dificulta a descoberta dos serviços e o contato de novos clientes'},{id:'site-antigo',name:'Site desatualizado',angle:'o site atual pode deixar informações importantes escondidas e dificultar pedidos de orçamento'},{id:'instagram',name:'Só usa redes sociais',angle:'o Instagram atrai interesse, mas um site pode organizar serviços, perguntas e contato em um endereço próprio'},{id:'agenda',name:'Precisa de agendamentos',angle:'uma página clara para serviços e agendamentos pode reduzir dúvidas antes do primeiro contato'},{id:'local',name:'Negócio local',angle:'quem pesquisa pela região precisa encontrar serviços, localização e uma forma rápida de falar com a empresa'},{id:'indicacao',name:'Vive de indicação',angle:'um site pode ajudar quem recebe uma indicação a conferir serviços e entrar em contato com mais segurança'}] as const;
export const salesObjectives=[{id:'reuniao',name:'Marcar conversa'},{id:'diagnostico',name:'Enviar diagnóstico'},{id:'demonstracao',name:'Mostrar uma ideia'},{id:'proposta',name:'Enviar proposta'}] as const;
const starts:Record<string,string>={whatsapp:'Olá [Nome], tudo bem? Sou [Seu Nome]. Encontrei a [Empresa] e achei interessante o trabalho de vocês.',instagram:'Oi [Nome]! Vi o perfil da [Empresa] por aqui e gostei de como vocês apresentam o negócio.',ligacao:'Olá, falo com [Nome]? Aqui é [Seu Nome]. Posso tomar um minuto? Encontrei a [Empresa] e queria compartilhar uma observação.',linkedin:'Olá [Nome], conheci a atuação da [Empresa] e gostaria de trocar uma ideia sobre a presença digital de vocês.',email:'Assunto: Uma ideia para a [Empresa]\n\nOlá [Nome], sou [Seu Nome] e conheci o trabalho da [Empresa]. Tenho uma observação breve sobre a experiência digital de vocês.'};
const endings:Record<string,string>={reuniao:'Podemos conversar por 15 minutos nesta semana para entender suas prioridades?',diagnostico:'Posso te enviar um diagnóstico curto com os pontos que observei?',demonstracao:'Quer que eu te mostre uma ideia visual pensada para a [Empresa]?',proposta:'Se fizer sentido, posso preparar escopo, prazo e investimento para você avaliar?'};
export function makeSalesScript(channel:string,situation:string,objective:string):SalesStage[]{
 const opening=starts[channel]||starts['whatsapp']||'Olá [Nome], sou [Seu Nome] e conheci a [Empresa].';const insight=salesSituations.find(x=>x.id===situation)?.angle||'a presença digital pode ser mais clara para novos clientes';const next=endings[objective]||endings['reuniao'];
 const prefix=channel==='email'?'':'[Nome], ';
 return [
 {title:'Saudação e permissão',purpose:'Abra sem pressão e peça espaço para conversar.',text:`${opening} Posso compartilhar uma observação rápida?`,tip:'Espere a pessoa aceitar. Se não houver resposta, não envie toda a sequência de uma vez.'},
 {title:'Conexão com o negócio',purpose:'Mostre que a mensagem não é genérica.',text:`${prefix}o que me chamou atenção foi [Detalhe observado]. Trabalho com sites para negócios que querem deixar seus serviços mais claros e fáceis de encontrar.`,tip:'Troque [Detalhe observado] por algo real visto no perfil, site ou avaliações.'},
 {title:'Diagnóstico aberto',purpose:'Entenda o cenário antes de propor.',text:`Hoje, como as pessoas chegam até a [Empresa]? Elas encontram as informações de que precisam e conseguem pedir orçamento sem dificuldade?`,tip:'Ouça a resposta e anote a principal dificuldade com as palavras do cliente.'},
 {title:'Resposta ao cenário',purpose:'Conecte a dificuldade relatada com uma oportunidade.',text:`Entendi. Pelo que você contou sobre [Dificuldade relatada], talvez exista uma oportunidade: ${insight}. Isso também acontece com vocês?`,tip:'Não afirme que encontrou um problema que não verificou. Ajuste à resposta recebida.'},
 {title:'Apresentação de valor',purpose:'Apresente a ideia sem prometer resultados.',text:`Uma possibilidade seria criar para a [Empresa] um site enxuto com apresentação dos serviços, respostas às dúvidas frequentes, provas reais e contato direto por WhatsApp. Assim, quem chegar pelo Google ou pelas redes encontra tudo em um só lugar.`,tip:'Cite somente funcionalidades compatíveis com o projeto e evite prometer aumento garantido de vendas.'},
 {title:'Convite para próximo passo',purpose:'Peça uma ação pequena e clara.',text:next,tip:'Ofereça um horário ou formato concreto se a pessoa demonstrar interesse.'},
 {title:'Se disser “já tenho site”',purpose:'Reconheça a objeção e investigue.',text:`Ótimo, isso já é um bom começo. Hoje o site da [Empresa] facilita o contato e mostra os serviços de forma atualizada? Se estiver funcionando bem, não faz sentido mudar por mudar.`,tip:'Não critique o site sem antes analisar.'},
 {title:'Se disser “está caro”',purpose:'Retome escopo e prioridades.',text:`Entendo. Antes de falar de valor, vale separar o essencial do que pode ficar para depois. Qual resultado ou informação seria indispensável na primeira versão? Posso montar uma opção mais enxuta para avaliar.`,tip:'Não conceda desconto sem ajustar escopo ou prazo.'},
 {title:'Se disser “agora não”',purpose:'Respeite o momento e combine retorno.',text:`Sem problema, [Nome]. Qual seria um momento melhor para eu retomar esse assunto? Posso deixar a ideia registrada e falar com você mais perto dessa data.`,tip:'Anote a data combinada; não envie lembretes sem permissão.'},
 {title:'Proposta e confirmação',purpose:'Converta interesse em uma decisão informada.',text:`Com o que conversamos, posso enviar uma proposta para a [Empresa] com páginas, entregáveis, prazo, revisões e investimento separados. Se estiver tudo alinhado, marcamos o início. Qual contato você prefere para receber?`,tip:'Confirme escopo, preço e condições por escrito antes de iniciar.'},
 {title:'Acompanhamento',purpose:'Retome com contexto, sem insistência.',text:`Oi [Nome], tudo bem? Retomando nossa conversa sobre [Prioridade combinada]: conseguiu olhar o material? Se tiver dúvidas sobre escopo ou investimento, posso esclarecer por aqui.`,tip:'Faça um acompanhamento depois de um prazo razoável e respeite uma recusa.'},
 {title:'Encerramento respeitoso',purpose:'Feche o ciclo e preserve a relação.',text:`Obrigado pelo tempo, [Nome]. Vou encerrar meu contato por agora. Se a [Empresa] decidir rever o site no futuro, fico à disposição. Sucesso por aí!`,tip:'Use esta etapa se não houver interesse ou após tentativas de acompanhamento sem resposta.'}
 ];
}
export function personalizeSales(text:string,values:{person:string;company:string;seller:string;detail:string}){return text.replaceAll('[Nome]',values.person||'[Nome]').replaceAll('[Empresa]',values.company||'[Empresa]').replaceAll('[Seu Nome]',values.seller||'[Seu Nome]').replaceAll('[Detalhe observado]',values.detail||'[Detalhe observado]')}
