import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Search, MapPin, Camera, Target, Zap, Star, Globe, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";

export const Route=createFileRoute("/_authenticated/prospecting")({component:ProspectingPage});
function ProspectingPage(){
 const [niche,setNiche]=useState(''); const [city,setCity]=useState(''); const [site,setSite]=useState(''); const [instagram,setInstagram]=useState(''); const [rating,setRating]=useState(''); const [size,setSize]=useState('');
 const score=useMemo(()=>{let n=0;if(niche)n+=20;if(city)n+=15;if(site==='Não')n+=30;if(instagram==='Sim')n+=15;if(rating==='3-4')n+=15;if(size==='Médio/alto')n+=5;return Math.min(100,n)},[niche,city,site,instagram,rating,size]);
 const maps=()=>{if(!niche||!city){toast.error('Informe nicho e cidade.');return}window.open(`https://www.google.com/maps/search/${encodeURIComponent(`${niche} em ${city}`)}`,'_blank')};
 const ig=()=>{if(!niche){toast.error('Informe o nicho.');return}window.open(`https://www.instagram.com/explore/search/keyword/?q=${encodeURIComponent(niche)}`,'_blank')};
 return <div className="max-w-6xl mx-auto space-y-8 pb-20"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#8A6A00]">Prime Prospect</p><h1 className="text-4xl md:text-5xl font-black tracking-tighter mt-2">Radar de Clientes</h1><p className="text-muted-foreground mt-2">Encontre negócios, avalie a presença digital e transforme pesquisa em oportunidade.</p></div>
 <Card className="p-6 md:p-8 border-[#FFD600]/40"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-[#FFD600] flex items-center justify-center text-[#111]"><Search/></div><div><h2 className="text-xl font-black">Encontrar oportunidades</h2><p className="text-xs text-muted-foreground">Pesquise por nicho e região sem depender de banco de dados.</p></div></div><div className="grid md:grid-cols-2 gap-5 mt-6"><div><label className="text-xs font-bold">Nicho</label><Input className="mt-2" value={niche} onChange={e=>setNiche(e.target.value)} placeholder="Ex.: clínica odontológica"/></div><div><label className="text-xs font-bold">Cidade / região</label><Input className="mt-2" value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: Curitiba - PR"/></div></div><div className="grid md:grid-cols-2 gap-3 mt-5"><Button onClick={maps} className="h-12 bg-[#FFD600] text-[#111] hover:bg-[#FFDF00] font-black"><MapPin className="mr-2 h-5 w-5"/> Pesquisar no Google Maps</Button><Button onClick={ig} variant="outline" className="h-12 border-[#FFD600]/50 font-black"><Camera className="mr-2 h-5 w-5 text-[#FFD600]"/> Explorar no Instagram</Button></div></Card>
 <div className="grid lg:grid-cols-[1fr_280px] gap-6"><Card className="p-6 md:p-8"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#8A6A00]">Qualificador</p><h2 className="text-2xl font-black">Vale abordar este lead?</h2></div><Target className="h-7 w-7 text-[#FFD600]"/></div><div className="grid md:grid-cols-2 gap-5 mt-6"><div><label className="text-xs font-bold">Tem site?</label><div className="grid grid-cols-3 gap-2 mt-2">{['Sim','Não','Ruim'].map(x=><button key={x} onClick={()=>setSite(x)} className={`rounded-xl border p-3 text-xs font-black ${site===x?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border'}`}>{x}</button>)}</div></div><div><label className="text-xs font-bold">Instagram ativo?</label><div className="grid grid-cols-2 gap-2 mt-2">{['Sim','Não'].map(x=><button key={x} onClick={()=>setInstagram(x)} className={`rounded-xl border p-3 text-xs font-black ${instagram===x?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border'}`}>{x}</button>)}</div></div><div><label className="text-xs font-bold">Avaliação no Maps</label><div className="grid grid-cols-2 gap-2 mt-2">{['3-4','4-5'].map(x=><button key={x} onClick={()=>setRating(x)} className={`rounded-xl border p-3 text-xs font-black ${rating===x?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border'}`}><Star className="inline h-3 w-3 text-[#FFD600] mr-1"/>{x}</button>)}</div></div><div><label className="text-xs font-bold">Porte percebido</label><div className="grid grid-cols-2 gap-2 mt-2">{['Pequeno','Médio/alto'].map(x=><button key={x} onClick={()=>setSize(x)} className={`rounded-xl border p-3 text-xs font-black ${size===x?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border'}`}>{x}</button>)}</div></div></div><div className="mt-6 rounded-2xl bg-background border border-border p-5"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-widest">Score de oportunidade</span><strong className="text-3xl">{score}<span className="text-sm text-muted-foreground">/100</span></strong></div><div className="mt-3 h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-[#FFD600] transition-all" style={{width:`${score}%`}}/></div><p className="text-xs text-muted-foreground mt-3">Use o score como apoio à triagem. A decisão final depende da análise real do negócio.</p></div></Card>
 <div className="space-y-4"><Card className="p-5"><Globe className="h-6 w-6 text-[#FFD600]"/><p className="font-black mt-3">Checklist rápido</p><ul className="text-xs text-muted-foreground space-y-2 mt-3"><li>• Site lento ou inexistente</li><li>• CTA difícil de encontrar</li><li>• Instagram sem link estratégico</li><li>• Google sem informações completas</li><li>• Oferta difícil de entender</li></ul></Card><Card className="p-5 bg-[#FFFBE6] dark:bg-[#2a2608] border-[#FFD600]/40"><Zap className="h-6 w-6 text-[#FFD600]"/><p className="font-black mt-3">Próximo passo</p><p className="text-xs text-muted-foreground mt-2">Depois de encontrar o lead, abra Scripts e escolha o canal de abordagem.</p></Card></div></div>
 <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black">Mini diagnóstico para enviar</p><p className="text-xs text-muted-foreground">Gere uma abertura baseada no que você observou.</p></div><Button variant="outline" onClick={()=>{const t=`Olá [Nome], analisei rapidamente a presença digital da ${niche||'[Empresa]'} em ${city||'[Cidade]'} e encontrei alguns pontos que podem melhorar a jornada de quem chega até vocês. Posso te mostrar uma análise curta?`;navigator.clipboard.writeText(t);toast.success('Mensagem copiada!')}}><Copy className="mr-2 h-4 w-4"/> Copiar abordagem</Button></div></Card>
 </div>;
}