import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Calculator, Check, Copy, MapPin, MessageSquare, Search, TrendingUp, Wand2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { makeSalesScript, personalizeSales, salesChannels, salesObjectives, salesSituations } from '@/lib/sales-scripts';
import { formatMoney, nicheAdjustments, pricingExtras, pricingTiers } from '@/lib/pricing-catalog';

export const Route=createFileRoute('/_authenticated/project')({head:()=>({meta:[{title:'Novo projeto — Prime'},{name:'description',content:'Prospete, crie, venda, precifique e escale em um único fluxo.'},{property:'og:title',content:'Novo projeto — Prime'},{property:'og:description',content:'Conduza um projeto de site do nicho ao fechamento.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:ProjectPage});

const niches=['Clínicas','Odontologia','Estética','Restaurantes','Advocacia','Imobiliárias','Academias','Arquitetura','Consultoria','Educação','Eventos','Pet shops','Contabilidade','Hotelaria','Outro'];
const objectives=['Gerar contatos','Receber orçamentos','Agendamentos','Apresentar serviços','Vender produtos','Mostrar portfólio','Outro'];
const stepInfo=[
  {title:'Escolha o nicho',description:'Defina onde e quem você vai prospectar.',icon:Search},
  {title:'Encontre o cliente',description:'Registre uma oportunidade real.',icon:MapPin},
  {title:'Crie o site',description:'Monte o briefing e o prompt.',icon:Wand2},
  {title:'Conduza a venda',description:'Avance pela conversa até fechar.',icon:MessageSquare},
  {title:'Defina o preço',description:'Escolha o pacote e ajuste o valor.',icon:Calculator},
  {title:'Prepare a escala',description:'Transforme a entrega em processo.',icon:TrendingUp},
];
const scaleActions=['Pesquisar 20 empresas do mesmo nicho','Fazer 5 contatos personalizados por dia','Criar uma demonstração reutilizável para o nicho','Usar checklist de briefing, revisão e entrega','Oferecer manutenção com tarefas e limites claros','Pedir feedback, portfólio e indicações após a entrega'];
type ProjectDraft={stage:number;nicheChoice:string;customNiche:string;city:string;company:string;contact:string;observation:string;objectiveChoice:string;customObjective:string;context:string;audience:string;benefit:string;channel:string;situation:string;salesObjective:string;person:string;seller:string;scriptIndex:number;tierId:string;nichePriceId:string;extras:string[];scaleChecks:string[]};
const initialDraft:ProjectDraft={stage:0,nicheChoice:'custom',customNiche:'',city:'',company:'',contact:'',observation:'',objectiveChoice:'custom',customObjective:'',context:'',audience:'',benefit:'',channel:'whatsapp',situation:'sem-site',salesObjective:'reuniao',person:'',seller:'',scriptIndex:0,tierId:'intermediate',nichePriceId:'local',extras:[],scaleChecks:[]};

function ProjectPage(){
  const [draft,setDraft]=useState<ProjectDraft>(initialDraft);
  const [ready,setReady]=useState(false);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('prime-project-data')||'null');if(saved&&typeof saved==='object')setDraft({...initialDraft,...saved})}catch{}setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem('prime-project-data',JSON.stringify(draft))},[draft,ready]);
  const update=<K extends keyof ProjectDraft>(key:K,value:ProjectDraft[K])=>setDraft(current=>({...current,[key]:value}));
  const niche=draft.nicheChoice==='custom'?draft.customNiche.trim():draft.nicheChoice;
  const objective=draft.objectiveChoice==='custom'?draft.customObjective.trim():draft.objectiveChoice;
  const stages=makeSalesScript(draft.channel,draft.situation,draft.salesObjective);
  const currentScript=stages[draft.scriptIndex]??stages[0];
  const selectedTier=pricingTiers.find(item=>item.id===draft.tierId)??pricingTiers[2];
  const selectedNichePrice=nicheAdjustments.find(item=>item.id===draft.nichePriceId)??nicheAdjustments[0];
  const suggestedPrice=useMemo(()=>selectedTier.price+selectedNichePrice.amount+pricingExtras.filter(item=>draft.extras.includes(item.id)).reduce((sum,item)=>sum+item.price,0),[selectedTier,selectedNichePrice,draft.extras]);
  const prompt=`CRIE UM SITE PROFISSIONAL PARA:\nEmpresa: ${draft.company||'[Empresa]'}\nNicho: ${niche||'[Nicho]'}\nRegião: ${draft.city||'[Região]'}\nObjetivo: ${objective||'Gerar contatos'}\nPúblico: ${draft.audience||'[Público-alvo]'}\nDiferencial: ${draft.benefit||'[Diferencial]'}\nContexto: ${draft.context||draft.observation||'[Contexto do negócio]'}\n\nCrie uma experiência personalizada, responsiva e orientada à conversão. Organize proposta de valor, serviços, provas reais, perguntas frequentes e chamadas para ação por WhatsApp. Não invente dados, avaliações ou resultados.`;
  const canAdvance=()=>draft.stage===0?Boolean(niche&&draft.city.trim()):draft.stage===1?Boolean(draft.company.trim()&&draft.observation.trim()):draft.stage===2?Boolean(objective&&draft.context.trim()):draft.stage===3?Boolean(draft.channel&&draft.situation&&draft.salesObjective):true;
  const advance=()=>{if(!canAdvance()){toast.error(draft.stage===0?'Informe nicho e região.':draft.stage===1?'Informe empresa e observação.':'Preencha os campos principais desta etapa.');return}if(draft.stage<stepInfo.length-1){update('stage',draft.stage+1);toast.success('Etapa concluída!')}else toast.success('Projeto concluído!')};
  const copy=async(text:string,label:string)=>{try{await navigator.clipboard.writeText(text);toast.success(`${label} copiado!`)}catch{toast.error('Não foi possível copiar.')}};
  const openMaps=()=>{if(!niche||!draft.city){toast.error('Informe nicho e região.');return}window.open(`https://www.google.com/maps/search/${encodeURIComponent(`${niche} em ${draft.city}`)}`,'_blank','noopener,noreferrer')};
  const CurrentIcon=stepInfo[draft.stage]?.icon??Search;
  return <div className="mx-auto max-w-6xl space-y-7 pb-20">
    <div><p className="text-xs font-black uppercase text-primary">Prime · Projeto guiado</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Seu projeto, do início à escala</h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Faça tudo aqui. Confirme cada etapa e avance sem abrir outra página.</p></div>
    <div className="grid grid-cols-3 gap-2 md:grid-cols-6">{stepInfo.map((item,index)=>{const Icon=item.icon;return <Button key={item.title} variant={draft.stage===index?'default':'outline'} className="h-auto min-h-20 flex-col gap-1 whitespace-normal p-2 text-center" onClick={()=>index<=draft.stage&&update('stage',index)} disabled={index>draft.stage}><span className="flex items-center gap-1 text-xs"><Icon className="h-4 w-4"/>{index<draft.stage&&<Check className="h-3 w-3"/>}</span><span className="text-[11px] leading-4">{item.title}</span></Button>})}</div>
    <Card className="overflow-hidden border-primary/40"><div className="border-b border-border bg-muted/50 p-5 md:p-7"><p className="text-xs font-black uppercase text-primary">Etapa {draft.stage+1} de {stepInfo.length}</p><h2 className="mt-2 flex items-center gap-2 text-2xl font-black"><CurrentIcon className="h-6 w-6 text-primary"/>{stepInfo[draft.stage]?.title}</h2><p className="mt-1 text-sm text-muted-foreground">{stepInfo[draft.stage]?.description}</p></div><div className="p-5 md:p-7">
      {draft.stage===0&&<div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Nicho para prospectar</Label><Select value={draft.nicheChoice} onValueChange={value=>update('nicheChoice',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="custom">Digitar outro nicho</SelectItem>{niches.filter(item=>item!=='Outro').map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select>{draft.nicheChoice==='custom'&&<Input autoFocus value={draft.customNiche} onChange={event=>update('customNiche',event.target.value)} placeholder="Digite o nicho que deseja atender"/>}</div><label className="text-sm font-bold">Cidade ou região<Input className="mt-2" value={draft.city} onChange={event=>update('city',event.target.value)} placeholder="Ex.: Campinas - SP"/></label></div><div className="border-l-4 border-primary bg-muted p-4 text-sm text-muted-foreground">Começar por um nicho deixa sua pesquisa, demonstração e abordagem mais específicas.</div></div>}
      {draft.stage===1&&<div className="space-y-5"><Button onClick={openMaps}><MapPin className="h-4 w-4"/> Pesquisar empresas no Maps</Button><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Empresa encontrada<Input className="mt-2" value={draft.company} onChange={event=>update('company',event.target.value)} placeholder="Nome do negócio"/></label><label className="text-sm font-bold">Contato encontrado<Input className="mt-2" value={draft.contact} onChange={event=>update('contact',event.target.value)} placeholder="WhatsApp, Instagram ou e-mail"/></label></div><label className="block text-sm font-bold">Oportunidade observada<Textarea className="mt-2 min-h-28" value={draft.observation} onChange={event=>update('observation',event.target.value)} placeholder="Ex.: não possui site e os serviços estão difíceis de encontrar"/></label></div>}
      {draft.stage===2&&<div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Objetivo do site</Label><Select value={draft.objectiveChoice} onValueChange={value=>update('objectiveChoice',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="custom">Digitar outro objetivo</SelectItem>{objectives.filter(item=>item!=='Outro').map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select>{draft.objectiveChoice==='custom'&&<Input autoFocus value={draft.customObjective} onChange={event=>update('customObjective',event.target.value)} placeholder="Digite o objetivo principal"/>}</div><label className="text-sm font-bold">Público-alvo<Input className="mt-2" value={draft.audience} onChange={event=>update('audience',event.target.value)} placeholder="Quem precisa ser convencido?"/></label><label className="text-sm font-bold md:col-span-2">Diferencial da empresa<Input className="mt-2" value={draft.benefit} onChange={event=>update('benefit',event.target.value)} placeholder="Por que escolher esta empresa?"/></label></div><label className="block text-sm font-bold">Contexto do negócio<Textarea className="mt-2 min-h-32" value={draft.context} onChange={event=>update('context',event.target.value)} placeholder="Serviços, público, diferenciais, provas, localização e oferta"/></label><div className="border border-primary bg-muted/40 p-4"><p className="font-black">Prompt preparado</p><pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap text-xs leading-6">{prompt}</pre><Button className="mt-4" variant="outline" onClick={()=>void copy(prompt,'Prompt')}><Copy className="h-4 w-4"/> Copiar prompt</Button></div></div>}
      {draft.stage===3&&<div className="space-y-5"><div><Label>Canal da conversa</Label><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-5">{salesChannels.map(item=><Button key={item.id} variant={draft.channel===item.id?'default':'outline'} className="h-auto min-h-12 whitespace-normal" onClick={()=>{update('channel',item.id);update('scriptIndex',0)}}>{item.name}</Button>)}</div></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Situação</Label><Select value={draft.situation} onValueChange={value=>{update('situation',value);update('scriptIndex',0)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{salesSituations.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Próximo objetivo</Label><Select value={draft.salesObjective} onValueChange={value=>{update('salesObjective',value);update('scriptIndex',0)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{salesObjectives.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><label className="text-sm font-bold">Nome do contato<Input className="mt-2" value={draft.person} onChange={event=>update('person',event.target.value)} placeholder="Nome da pessoa"/></label><label className="text-sm font-bold">Seu nome<Input className="mt-2" value={draft.seller} onChange={event=>update('seller',event.target.value)} placeholder="Como você se apresenta"/></label></div>{currentScript&&<div className="border border-primary p-5"><p className="text-xs font-black uppercase text-primary">Conversa {draft.scriptIndex+1} de {stages.length}</p><h3 className="mt-1 text-xl font-black">{currentScript.title}</h3><p className="mt-2 text-sm text-muted-foreground">{currentScript.purpose}</p><div className="mt-4 border-l-4 border-primary bg-muted p-4 text-sm leading-7">{personalizeSales(currentScript.text,{person:draft.person,company:draft.company,seller:draft.seller,detail:draft.observation})}</div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={()=>void copy(personalizeSales(currentScript.text,{person:draft.person,company:draft.company,seller:draft.seller,detail:draft.observation}),'Etapa')}><Copy className="h-4 w-4"/> Copiar</Button><Button variant="outline" disabled={draft.scriptIndex===0} onClick={()=>update('scriptIndex',draft.scriptIndex-1)}><ArrowLeft className="h-4 w-4"/> Anterior</Button><Button variant="outline" disabled={draft.scriptIndex===stages.length-1} onClick={()=>update('scriptIndex',draft.scriptIndex+1)}>Próxima resposta <ArrowRight className="h-4 w-4"/></Button></div></div>}</div>}
      {draft.stage===4&&<div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{pricingTiers.map(item=><Button key={item.id} variant={draft.tierId===item.id?'default':'outline'} className="h-auto min-h-28 flex-col whitespace-normal p-3 text-center" onClick={()=>update('tierId',item.id)}><span>{item.name}</span><strong className="text-xl">{formatMoney(item.price)}</strong></Button>)}</div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Tipo de cliente</Label><Select value={draft.nichePriceId} onValueChange={value=>update('nichePriceId',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{nicheAdjustments.map(item=><SelectItem key={item.id} value={item.id}>{item.name}{item.amount?` · + ${formatMoney(item.amount)}`:''}</SelectItem>)}</SelectContent></Select></div><div><Label>Adicionais</Label><div className="mt-2 grid grid-cols-2 gap-2">{pricingExtras.map(item=><Button key={item.id} variant={draft.extras.includes(item.id)?'default':'outline'} className="h-auto whitespace-normal text-xs" onClick={()=>update('extras',draft.extras.includes(item.id)?draft.extras.filter(id=>id!==item.id):[...draft.extras,item.id])}>{item.name}</Button>)}</div></div></div><div className="border border-primary bg-muted/40 p-5"><p className="text-xs font-black uppercase text-muted-foreground">Valor indicado</p><p className="mt-1 text-4xl font-black">{formatMoney(suggestedPrice)}</p><p className="mt-2 text-sm text-muted-foreground">{selectedTier.description} Cobre mais quando houver mais páginas, urgência, textos, integrações ou revisões.</p></div></div>}
      {draft.stage===5&&<div className="space-y-3"><p className="text-sm text-muted-foreground">Marque as ações que vai aplicar para repetir o processo com consistência.</p>{scaleActions.map(action=><Button key={action} variant={draft.scaleChecks.includes(action)?'default':'outline'} className="h-auto min-h-14 w-full justify-start whitespace-normal text-left" onClick={()=>update('scaleChecks',draft.scaleChecks.includes(action)?draft.scaleChecks.filter(item=>item!==action):[...draft.scaleChecks,action])}>{draft.scaleChecks.includes(action)?<Check className="h-4 w-4 shrink-0"/>:<span className="h-4 w-4 shrink-0 border border-current"/>}{action}</Button>)}</div>}
    </div><div className="flex flex-wrap justify-between gap-3 border-t border-border p-5 md:px-7"><Button variant="outline" disabled={draft.stage===0} onClick={()=>update('stage',Math.max(0,draft.stage-1))}><ArrowLeft className="h-4 w-4"/> Voltar</Button><Button onClick={advance}>{draft.stage===stepInfo.length-1?'Concluir projeto':'Confirmar e avançar'} <ArrowRight className="h-4 w-4"/></Button></div></Card>
  </div>;
}