import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Calculator, TrendingUp, Download, Copy, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/pricing-calculator")({head:()=>({meta:[{title:"Precificação — Prime"},{name:"description",content:"Calcule preço, custos, margem e impostos do projeto."},{property:"og:title",content:"Precificação — Prime"},{property:"og:description",content:"Monte uma proposta segura e lucrativa."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:PricingCalculatorPage});
function PricingCalculatorPage(){
 const [pages,setPages]=useState(5),[complexity,setComplexity]=useState(2),[hourlyRate,setHourlyRate]=useState(120),[toolCosts,setToolCosts]=useState(250),[taxRate,setTaxRate]=useState(6),[extras,setExtras]=useState<string[]>([]);
 const extraMap:Record<string,number>={Blog:800,Agendamento:900,WhatsApp:300,SEO:700,Ecommerce:2500};
 const result=useMemo(()=>{let base=pages*300*(complexity===1?1:complexity===2?1.5:2.5);extras.forEach(x=>base+=extraMap[x] ?? 0);const hours=pages*(complexity===1?4:complexity===2?8:16);const labor=hours*hourlyRate;const subtotal=Math.max(base,labor)+toolCosts;const total=subtotal/(1-taxRate/100);const tax=total*taxRate/100;const profit=total-tax-toolCosts-labor;return{hours,total,tax,labor,profit,margin:(profit/total)*100};},[pages,complexity,hourlyRate,toolCosts,taxRate,extras]);
 const toggle=(x:string)=>setExtras(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]); const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
 const copy=()=>{navigator.clipboard.writeText(`Projeto Prime\nPáginas: ${pages}\nComplexidade: ${complexity===1?'Simples':complexity===2?'Profissional':'Premium'}\nRecursos: ${extras.join(', ')||'Nenhum'}\nInvestimento sugerido: ${money(result.total)}`);toast.success('Resumo copiado!')};
 return <div className="max-w-6xl mx-auto space-y-8 pb-20"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#8A6A00]">Prime Finance</p><h1 className="text-4xl md:text-5xl font-black tracking-tighter mt-2">Precificação inteligente</h1><p className="text-muted-foreground mt-2">Monte o preço com custo, esforço, impostos, margem e recursos extras.</p></div><div className="flex gap-2"><Button variant="outline" onClick={copy}><Copy className="mr-2 h-4 w-4"/> Copiar resumo</Button><Button className="bg-[#FFD600] text-[#111] hover:bg-[#FFDF00]" onClick={()=>toast.success('Resumo preparado para exportação.')}><Download className="mr-2 h-4 w-4"/> Exportar</Button></div></div>
 <div className="grid lg:grid-cols-[1fr_380px] gap-6"><Card className="p-6 md:p-8"><CardHeader className="px-0 pt-0"><CardTitle className="flex items-center gap-2"><Calculator className="h-5 w-5 text-[#FFD600]"/> Configuração do projeto</CardTitle></CardHeader><CardContent className="px-0 space-y-8"><div className="space-y-4"><div className="flex justify-between"><Label>Páginas</Label><strong>{pages}</strong></div><Slider value={[pages]} onValueChange={v=>{const value=v[0];if(value!==undefined)setPages(value)}} min={1} max={40}/></div><div><Label>Complexidade</Label><div className="grid grid-cols-3 gap-2 mt-3">{[[1,'Simples'],[2,'Profissional'],[3,'Premium']].map(([v,l])=><button key={String(v)} onClick={()=>setComplexity(Number(v))} className={`rounded-xl border p-3 text-xs font-black ${complexity===v?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border'}`}>{l}</button>)}</div></div><div className="grid md:grid-cols-2 gap-5"><div><Label>Valor da sua hora: R$ {hourlyRate}</Label><Slider className="mt-4" value={[hourlyRate]} onValueChange={v=>{const value=v[0];if(value!==undefined)setHourlyRate(value)}} min={30} max={500} step={10}/></div><div><Label>Custos fixos: R$ {toolCosts}</Label><Slider className="mt-4" value={[toolCosts]} onValueChange={v=>{const value=v[0];if(value!==undefined)setToolCosts(value)}} min={0} max={3000} step={50}/></div></div><div><Label>Impostos: {taxRate}%</Label><Slider className="mt-4" value={[taxRate]} onValueChange={v=>{const value=v[0];if(value!==undefined)setTaxRate(value)}} min={0} max={30} step={0.5}/></div><div><Label>Recursos extras</Label><div className="grid sm:grid-cols-2 gap-2 mt-3">{Object.entries(extraMap).map(([name,price])=><button key={name} onClick={()=>toggle(name)} className={`flex items-center justify-between rounded-xl border p-3 text-xs font-bold ${extras.includes(name)?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border'}`}>{name}<span>+ {money(price)}</span></button>)}</div></div></CardContent></Card>
 <Card className="overflow-hidden border-[#FFD600]/40"><div className="bg-[#FFD600] text-[#111] p-6"><p className="text-[10px] font-black uppercase tracking-[.2em]">Investimento sugerido</p><div className="text-5xl font-black tracking-tight mt-2">{money(result.total)}</div><p className="text-xs font-bold mt-2 opacity-70">Estimativa para orientar sua proposta.</p></div><CardContent className="p-6 space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border p-4"><p className="text-[10px] text-muted-foreground uppercase font-black">Horas</p><p className="text-xl font-black mt-1">{result.hours}h</p></div><div className="rounded-xl border p-4"><p className="text-[10px] text-muted-foreground uppercase font-black">Margem</p><p className="text-xl font-black mt-1">{result.margin.toFixed(1)}%</p></div></div>{[['Custo de mão de obra',money(result.labor)],['Impostos',money(result.tax)],['Custos fixos',money(toolCosts)],['Lucro estimado',money(result.profit)]].map(([l,v])=><div key={l} className="flex justify-between text-sm border-b border-border/60 pb-2"><span className="text-muted-foreground">{l}</span><strong>{v}</strong></div>)}<div className="rounded-2xl bg-[#FFFBE6] dark:bg-[#2a2608] border border-[#FFD600]/40 p-4 flex gap-3"><CheckCircle2 className="h-5 w-5 text-[#FFD600] shrink-0"/><p className="text-xs font-medium">Use a calculadora como referência. Ajuste o valor final ao escopo, prazo, risco e valor percebido do projeto.</p></div><Button className="w-full bg-[#111] text-white hover:bg-black dark:bg-[#FFD600] dark:text-[#111]" onClick={copy}><TrendingUp className="mr-2 h-4 w-4"/> Copiar proposta</Button></CardContent></Card></div></div>;
}