import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ChevronLeft, ChevronRight, Copy, MessageSquare } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";
import { makeSalesScript, personalizeSales, salesChannels, salesSituations, salesObjectives } from "@/lib/sales-scripts";
export const Route=createFileRoute("/_authenticated/scripts")({head:()=>({meta:[{title:"Scripts de Venda — Prime"},{name:"description",content:"Roteiros completos de abordagem, objeções e fechamento."},{property:"og:title",content:"Scripts de Venda — Prime"},{property:"og:description",content:"Conduza conversas de venda passo a passo."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ScriptsPage});
function ScriptsPage(){
 const [channel,setChannel]=useState('');const [situation,setSituation]=useState('');const [objective,setObjective]=useState('');const [index,setIndex]=useState(0);const [person,setPerson]=useState('');const [company,setCompany]=useState('');const [seller,setSeller]=useState('');const [detail,setDetail]=useState('');
 const stages=channel&&situation&&objective?makeSalesScript(channel,situation,objective):[];const current=stages[index];const values={person,company,seller,detail};const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);toast.success('Copiado!')}catch{toast.error('Não foi possível copiar.')}};
 return <div className="mx-auto max-w-6xl space-y-7 pb-20"><div><p className="text-xs font-black uppercase text-primary">Prime Sales</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Scripts de Venda</h1><p className="mt-2 text-sm text-muted-foreground">Escolha o canal, a situação e o próximo objetivo. Avance pela conversa no ritmo do cliente.</p></div>
 <section><h2 className="mb-3 text-lg font-black">1 · Onde será a conversa?</h2><div className="grid grid-cols-2 gap-2 md:grid-cols-5">{salesChannels.map(x=><Button key={x.id} variant={channel===x.id?'default':'outline'} className="h-auto min-h-16 whitespace-normal text-left" onClick={()=>{setChannel(x.id);setIndex(0)}}>{x.name}</Button>)}</div></section>
 {channel&&<section><h2 className="mb-3 text-lg font-black">2 · Qual a situação do cliente?</h2><div className="grid grid-cols-2 gap-2 md:grid-cols-3">{salesSituations.map(x=><Button key={x.id} variant={situation===x.id?'default':'outline'} className="h-auto min-h-14 whitespace-normal text-left" onClick={()=>{setSituation(x.id);setIndex(0)}}>{x.name}</Button>)}</div></section>}
 {situation&&channel&&<section><h2 className="mb-3 text-lg font-black">3 · O que você quer conseguir?</h2><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{salesObjectives.map(x=><Button key={x.id} variant={objective===x.id?'default':'outline'} className="h-auto min-h-14 whitespace-normal" onClick={()=>{setObjective(x.id);setIndex(0)}}>{x.name}</Button>)}</div></section>}
 {current&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">Seu nome<Input className="mt-2" value={seller} onChange={e=>setSeller(e.target.value)} placeholder="Como você se apresenta"/></label><label className="text-xs font-bold">Nome do contato<Input className="mt-2" value={person} onChange={e=>setPerson(e.target.value)} placeholder="Nome da pessoa"/></label><label className="text-xs font-bold">Empresa<Input className="mt-2" value={company} onChange={e=>setCompany(e.target.value)} placeholder="Nome da empresa"/></label><label className="text-xs font-bold">Detalhe observado<Input className="mt-2" value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Algo real que você notou"/></label></section><Card className="border-primary/40 p-5 md:p-8"><div className="h-2 overflow-hidden bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${((index+1)/stages.length)*100}%`}}/></div><p className="mt-6 text-xs font-black uppercase text-muted-foreground">Etapa {index+1} de {stages.length}</p><h2 className="mt-1 text-2xl font-black">{current.title}</h2><p className="mt-2 text-sm text-muted-foreground">{current.purpose}</p><div className="mt-6 border-l-4 border-primary bg-muted/60 p-5 text-sm leading-7 whitespace-pre-wrap">{personalizeSales(current.text,values)}</div><p className="mt-4 text-xs text-muted-foreground">{current.tip}</p><div className="mt-6 flex flex-wrap gap-2"><Button onClick={()=>void copy(personalizeSales(current.text,values))}><Copy className="h-4 w-4"/> Copiar etapa</Button><Button variant="outline" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ChevronLeft className="h-4 w-4"/> Anterior</Button><Button variant="outline" disabled={index===stages.length-1} onClick={()=>setIndex(i=>i+1)}>Próxima <ChevronRight className="h-4 w-4"/></Button><Button variant="outline" onClick={()=>void copy(stages.map((s,i)=>`${i+1}. ${s.title}\n${personalizeSales(s.text,values)}`).join('\n\n'))}><Copy className="h-4 w-4"/> Roteiro completo</Button></div></Card></>}
 {!channel&&<div className="border border-dashed border-primary p-10 text-center"><MessageSquare className="mx-auto h-9 w-9 text-primary"/><p className="mt-3 font-bold">Escolha um canal para começar.</p></div>}</div>
}
