import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { Search, Wand2, MessageSquare, Calculator, TrendingUp, ArrowRight, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
export const Route=createFileRoute('/_authenticated/project')({head:()=>({meta:[{title:'Novo projeto — Prime'},{name:'description',content:'Da prospecção à escala, planeje sua venda de sites passo a passo.'},{property:'og:title',content:'Novo projeto — Prime'},{property:'og:description',content:'Organize cada etapa de um projeto de site.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:ProjectPage});
const steps=[{title:'Encontre o cliente',to:'/prospecting' as const,icon:Search,detail:'Pesquise um nicho e uma cidade no Radar. Observe um negócio real e anote o nome da empresa.'},{title:'Crie o site',to:'/ai-builder' as const,icon:Wand2,detail:'Preencha o negócio, nicho e objetivo. Gere um briefing sob medida para o site.'},{title:'Conduza a conversa',to:'/scripts' as const,icon:MessageSquare,detail:'Escolha o canal e a situação do cliente. Personalize e avance até o fechamento.'},{title:'Defina o preço',to:'/pricing-calculator' as const,icon:Calculator,detail:'Calcule escopo, horas e custos. Envie uma proposta coerente com o projeto.'},{title:'Escale a operação',to:'/scale' as const,icon:TrendingUp,detail:'Organize entregas, indicações e processos para vender com consistência.'}];
function ProjectPage(){const [name,setName]=useState('');const [stage,setStage]=useState(0);const [ready,setReady]=useState(false);useEffect(()=>{try{const item=JSON.parse(localStorage.getItem('prime-current-project')||'{}');if(typeof item.name==='string')setName(item.name);if(Number.isInteger(item.stage)&&item.stage>=0&&item.stage<steps.length)setStage(item.stage)}catch{}setReady(true)},[]);
 const persist=(nextName:string,nextStage:number)=>{setName(nextName);setStage(nextStage);localStorage.setItem('prime-current-project',JSON.stringify({name:nextName,stage:nextStage}))};
 return <div className="mx-auto max-w-5xl space-y-8 pb-20"><div><p className="text-xs font-black uppercase text-primary">Prime · Projeto</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Novo projeto</h1><p className="mt-3 text-sm text-muted-foreground">Encontre o cliente, prepare o site, converse, precifique e aprenda a escalar. Seu avanço fica salvo neste navegador.</p></div><label className="block max-w-xl text-sm font-bold">Nome da empresa ou projeto<Input className="mt-2" value={name} onChange={e=>{setName(e.target.value);if(ready)localStorage.setItem('prime-current-project',JSON.stringify({name:e.target.value,stage}))}} placeholder="Ex.: Clínica Horizonte"/></label><div className="space-y-0 border-l-2 border-border pl-5 md:pl-8">{steps.map((step,i)=>{const Icon=step.icon;return <section key={step.title} className="relative border-b border-border py-6"><span className={`absolute -left-[31px] top-8 flex h-5 w-5 items-center justify-center rounded-full border-2 md:-left-[43px] ${i<=stage?'border-primary bg-primary text-primary-foreground':'border-border bg-background'}`}>{i<stage?<Check className="h-3 w-3"/>:null}</span><div className="flex flex-wrap items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center bg-primary/15"><Icon className="h-5 w-5 text-foreground"/></div><div className="min-w-0 flex-1"><p className="text-xs font-bold text-muted-foreground">ETAPA {i+1}</p><h2 className="mt-1 text-xl font-black">{step.title}</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{step.detail}</p><div className="mt-4 flex flex-wrap gap-2"><Link to={step.to}><Button variant={stage===i?'default':'outline'}>Abrir {step.title.toLowerCase()} <ArrowRight className="h-4 w-4"/></Button></Link>{stage===i&&i<steps.length-1&&<Button variant="outline" onClick={()=>{persist(name,i+1);toast.success('Próxima etapa liberada')}}>Concluir e avançar <Check className="h-4 w-4"/></Button>}{stage===i&&i===steps.length-1&&<Button variant="outline" onClick={()=>toast.success('Projeto concluído!')}>Marcar como concluído <Check className="h-4 w-4"/></Button>}</div></div></div></section>})}</div></div>
}
