import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Shield, LogOut, Bell, User, Palette } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useQueryClient } from "@tanstack/react-query";
export const Route=createFileRoute("/_authenticated/profile")({head:()=>({meta:[{title:"Conta — Prime"},{name:"description",content:"Gerencie seu acesso e preferências Prime."},{property:"og:title",content:"Conta — Prime"},{property:"og:description",content:"Gerencie seu acesso Prime."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ProfilePage});
function ProfilePage(){const navigate=useNavigate();const queryClient=useQueryClient();const [email,setEmail]=useState('');useEffect(()=>{void supabase.auth.getUser().then(({data})=>setEmail(data.user?.email??''))},[]);const signOut=async()=>{await queryClient.cancelQueries();queryClient.clear();const{error}=await supabase.auth.signOut();if(error){toast.error('Não foi possível encerrar a sessão.');return}await navigate({to:'/auth',replace:true})};return <div className="mx-auto max-w-4xl space-y-7 pb-20"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">Conta Prime</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Minha conta</h1><p className="mt-2 text-muted-foreground">Acesso, segurança e preferências da plataforma.</p></div><div className="grid gap-6 lg:grid-cols-[280px_1fr]"><Card className="p-6 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center bg-primary text-2xl font-black text-primary-foreground">P</div><h2 className="mt-4 break-all text-base font-black">{email||'Conta Prime'}</h2><p className="mt-1 text-xs text-muted-foreground">Acesso ativo</p></Card><div className="space-y-5"><Card className="space-y-5 p-6"><div className="flex items-center gap-3"><User className="h-5 w-5 text-primary"/><div><h3 className="font-black">Dados de acesso</h3><p className="text-xs text-muted-foreground">Sua conta usa somente e-mail e senha.</p></div></div><div><label className="text-xs font-bold">E-mail</label><Input className="mt-2" value={email} readOnly/></div></Card><Card className="space-y-3 p-6">{[{icon:Shield,label:'Acesso protegido',desc:'As áreas internas exigem uma sessão válida.'},{icon:Bell,label:'Alertas da operação',desc:'Acompanhe as próximas ações pelo cabeçalho.'},{icon:Palette,label:'Tema persistente',desc:'Sua escolha de modo claro ou escuro fica salva.'}].map(x=><div key={x.label} className="flex items-center gap-4 border p-4"><x.icon className="h-5 w-5 text-primary"/><div><p className="text-sm font-bold">{x.label}</p><p className="mt-1 text-xs text-muted-foreground">{x.desc}</p></div></div>)}</Card><Button variant="destructive" onClick={signOut} className="w-full"><LogOut className="h-4 w-4"/> Encerrar sessão</Button></div></div></div>}
