import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Camera, Phone, BriefcaseBusiness, Mail, Copy, ChevronRight, ChevronLeft, MessageSquare, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/scripts")({ component: ScriptsPage });

type Script={title:string;text:string};
const channels=[
  {id:'instagram',name:'Instagram',desc:'Direct, comentários e abordagem visual',icon:Camera},
  {id:'whatsapp',name:'WhatsApp',desc:'Conversa direta e follow-up',icon:Phone},
  {id:'ligacao',name:'Ligação',desc:'Roteiro para conversa rápida',icon:Phone},
  {id:'linkedin',name:'LinkedIn',desc:'B2B e decisores',icon:BriefcaseBusiness},
  {id:'email',name:'E-mail',desc:'Cold mail e follow-up',icon:Mail},
];
const scriptsByChannel:Record<string,Script[]>={
 instagram:[{title:'Primeiro contato',text:'Olá [Nome]! Conheci a [Empresa] pelo Instagram e gostei muito do trabalho de vocês. Posso te mostrar uma oportunidade simples que encontrei na presença digital da empresa?'},{title:'Apresentação da oportunidade',text:'Analisei o perfil de vocês e percebi que um site mais estratégico poderia transformar o interesse que chega pelo Instagram em contatos e pedidos de orçamento. Quer que eu te mostre uma ideia?'},{title:'Follow-up',text:'Oi [Nome], passando para não deixar aquela análise se perder. Se fizer sentido, posso te enviar um exemplo pensado para a [Empresa].'}],
 whatsapp:[{title:'Abertura',text:'Olá [Nome], tudo bem? Sou [Seu Nome]. Trabalho com criação de sites estratégicos e encontrei a [Empresa]. Posso te mostrar rapidamente uma oportunidade que identifiquei?'},{title:'Diagnóstico',text:'O ponto principal é transformar a presença digital em uma jornada mais clara para quem chega: entender, confiar e entrar em contato. Posso te explicar em 2 minutos?'},{title:'Fechamento',text:'Se você gostar da proposta, posso montar o próximo passo com escopo, prazo e investimento para a [Empresa]. Quer receber?'},{title:'Follow-up',text:'Oi [Nome]! Só retomando nossa conversa. Ainda posso te enviar aquela proposta visual sem compromisso.'}],
 ligacao:[{title:'Abertura',text:'Olá, falo com [Nome]? Aqui é [Seu Nome]. Vou ser breve: encontrei a [Empresa] e trabalho com sites focados em transformar presença digital em oportunidades. Posso fazer uma pergunta rápida?'},{title:'Pergunta',text:'Hoje vocês recebem clientes principalmente por indicação, Instagram, Google ou já têm um site que gera contatos?'},{title:'Diagnóstico',text:'Entendi. A partir disso consigo te mostrar onde um site estratégico pode complementar o que vocês já fazem, sem substituir os canais que funcionam.'},{title:'Próximo passo',text:'Posso te enviar uma demonstração e, se fizer sentido, marcamos uma conversa para montar o projeto.'}],
 linkedin:[{title:'Conexão',text:'Olá [Nome], acompanho a atuação da [Empresa] e achei interessante conectar. Trabalho com experiências digitais para negócios que querem fortalecer posicionamento e aquisição.'},{title:'Valor',text:'Analisei rapidamente a presença digital da empresa e encontrei alguns pontos de melhoria. Posso compartilhar uma análise objetiva?'},{title:'Reunião',text:'Se a análise fizer sentido, podemos marcar uma conversa de 15 minutos para entender prioridades e próximos passos.'}],
 email:[{title:'Primeiro e-mail',text:'Assunto: Uma oportunidade na presença digital da [Empresa]\n\nOlá [Nome], analisei rapidamente a presença digital da [Empresa] e identifiquei uma oportunidade de melhorar a jornada de quem chega até vocês. Posso enviar um diagnóstico curto?'},{title:'Follow-up',text:'Assunto: Re: presença digital da [Empresa]\n\nOlá [Nome], passando apenas para confirmar se conseguiu ver minha mensagem. Se quiser, envio a análise em um único PDF.'},{title:'Último contato',text:'Assunto: Encerrando por aqui\n\nVou encerrar este contato para não ser inconveniente. Se melhorar o site ou a conversão digital entrar no radar, fico à disposição.'}]
};
const modes=[{id:'abordagem',label:'Abordagem inicial'},{id:'diagnostico',label:'Diagnóstico / valor'},{id:'followup',label:'Follow-up'},{id:'fechamento',label:'Fechamento'}];
function ScriptsPage(){
 const [channel,setChannel]=useState(''); const [scriptIndex,setScriptIndex]=useState(0); const [mode,setMode]=useState('');
 const scripts=useMemo(()=>scriptsByChannel[channel]||[],[channel]);
 const filtered=scripts.filter((_,i)=>mode==='followup'?i===scripts.length-1:mode==='fechamento'?i===scripts.length-1:i<2||mode==='diagnostico');
 const current=filtered[Math.min(scriptIndex,Math.max(0,filtered.length-1))];
 const chooseChannel=(id:string)=>{setChannel(id);setMode('');setScriptIndex(0)};
 return <div className="max-w-6xl mx-auto space-y-8 pb-20">
  <div><div className="flex items-center gap-2 text-[#8A6A00] text-[10px] font-black uppercase tracking-[.2em]"><Sparkles className="h-4 w-4 text-[#FFD600]"/> Prime Sales</div><h1 className="text-4xl md:text-5xl font-black tracking-tighter mt-2">Scripts de Venda</h1><p className="text-muted-foreground mt-2">Escolha o canal, depois o objetivo da conversa. A Prime conduz a mensagem etapa por etapa.</p></div>
  <div className="grid md:grid-cols-5 gap-3">{channels.map(c=>{const Icon=c.icon;return <button key={c.id} onClick={()=>chooseChannel(c.id)} className={`text-left rounded-2xl border p-4 transition-all ${channel===c.id?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608] shadow-[0_8px_30px_rgba(255,214,0,.12)]':'border-border bg-card hover:border-[#FFD600]/60'}`}><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#FFD600] text-[#111]"><Icon className="h-5 w-5"/></div><p className="font-black mt-3">{c.name}</p><p className="text-[11px] text-muted-foreground mt-1">{c.desc}</p></button>})}</div>
  {channel&&<Card className="p-6 md:p-8 border-[#FFD600]/50"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#8A6A00]">Canal selecionado</p><h2 className="text-2xl font-black">{channels.find(x=>x.id===channel)?.name}</h2></div><span className="rounded-full bg-[#FFD600] px-3 py-1 text-[10px] font-black text-[#111]">FLUXO GUIADO</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-6">{modes.map((m,i)=><button key={m.id} onClick={()=>{setMode(m.id);setScriptIndex(0)}} className={`rounded-xl border px-3 py-3 text-xs font-black transition ${mode===m.id?'border-[#FFD600] bg-[#FFFBE6] dark:bg-[#2a2608]':'border-border hover:border-[#FFD600]/60'}`}><span className="block text-[9px] text-muted-foreground mb-1">0{i+1}</span>{m.label}</button>)}</div>
  {current&&<div className="mt-7 grid lg:grid-cols-[1fr_280px] gap-5"><div className="rounded-2xl border border-border bg-background p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#8A6A00]">Mensagem {scriptIndex+1} de {filtered.length}</p><h3 className="text-xl font-black mt-1">{current.title}</h3></div><MessageSquare className="h-6 w-6 text-[#FFD600]"/></div><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-foreground">{current.text}</p><div className="flex flex-wrap gap-2 mt-6"><Button onClick={()=>{navigator.clipboard.writeText(current.text);toast.success('Mensagem copiada!')}} className="bg-[#FFD600] text-[#111] hover:bg-[#FFDF00]"><Copy className="mr-2 h-4 w-4"/> Copiar mensagem</Button><Button variant="outline" disabled={scriptIndex===0} onClick={()=>setScriptIndex(x=>Math.max(0,x-1))}><ChevronLeft className="mr-1 h-4 w-4"/> Anterior</Button><Button variant="outline" disabled={scriptIndex>=filtered.length-1} onClick={()=>setScriptIndex(x=>Math.min(filtered.length-1,x+1))}>Próxima <ChevronRight className="ml-1 h-4 w-4"/></Button></div></div><div className="rounded-2xl border border-border bg-card p-5"><p className="font-black">Como usar</p><div className="space-y-3 mt-4 text-xs text-muted-foreground"><p>1. Personalize [Nome] e [Empresa].</p><p>2. Envie uma etapa por vez.</p><p>3. Espere a resposta antes de avançar.</p><p>4. Adapte a conversa ao contexto real.</p></div><div className="mt-5 rounded-xl bg-[#FFFBE6] dark:bg-[#2a2608] border border-[#FFD600]/40 p-4"><p className="text-[10px] font-black uppercase text-[#8A6A00]">Próxima etapa</p><p className="text-xs font-bold mt-1">Não acelere o fechamento. Gere contexto primeiro.</p></div></div></div>}</Card>}
  {!channel&&<div className="rounded-3xl border border-dashed border-[#FFD600]/60 bg-[#FFFBE6] dark:bg-[#2a2608] p-10 text-center"><MessageSquare className="mx-auto h-10 w-10 text-[#FFD600]"/><h2 className="text-2xl font-black mt-4">Comece escolhendo o canal</h2><p className="text-sm text-muted-foreground mt-2">Instagram, WhatsApp, ligação, LinkedIn ou e-mail. Depois a Prime monta o fluxo da conversa.</p></div>}
 </div>;
}