import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Search, MapPin, Camera, Copy, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card } from '@/components/ui/card';
import { toast } from 'sonner';
export const Route=createFileRoute('/_authenticated/prospecting')({head:()=>({meta:[{title:'Radar de Clientes — Prime'},{name:'description',content:'Pesquise negócios e prepare abordagens personalizadas.'},{property:'og:title',content:'Radar de Clientes — Prime'},{property:'og:description',content:'Encontre oportunidades reais por nicho e região.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:ProspectingPage});
function ProspectingPage(){const [niche,setNiche]=useState(''),[city,setCity]=useState(''),[company,setCompany]=useState(''),[observation,setObservation]=useState(''),[contact,setContact]=useState('');
 const maps=()=>{if(!niche.trim()||!city.trim()){toast.error('Informe nicho e cidade.');return}window.open(`https://www.google.com/maps/search/${encodeURIComponent(`${niche} em ${city}`)}`,'_blank','noopener,noreferrer')};
 const instagram=()=>{if(!niche.trim()){toast.error('Informe o nicho.');return}window.open(`https://www.instagram.com/explore/search/keyword/?q=${encodeURIComponent(niche)}`,'_blank','noopener,noreferrer')};
 const message=`Olá [Nome], encontrei a ${company||'[Empresa]'} em ${city||'[Cidade]'} e observei ${observation||'[uma oportunidade na presença digital]'}. Trabalho com sites para negócios de ${niche||'[nicho]'}. Posso compartilhar uma ideia breve para facilitar o contato de novos clientes?`;
 return <div className="mx-auto max-w-6xl space-y-8 pb-20"><div><p className="text-xs font-black uppercase text-primary">Prime Prospect</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Radar de Clientes</h1><p className="mt-2 text-sm text-muted-foreground">Pesquise empresas reais, registre o que encontrou e prepare um contato relevante.</p></div><section className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="flex items-center gap-2 text-xl font-black"><Search className="h-5 w-5 text-primary"/> Encontrar oportunidades</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Nicho<Input className="mt-2" value={niche} onChange={e=>setNiche(e.target.value)} placeholder="Ex.: clínicas"/></label><label className="text-xs font-bold">Cidade / região<Input className="mt-2" value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: Curitiba - PR"/></label></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={maps}><MapPin className="h-4 w-4"/> Buscar no Maps</Button><Button variant="outline" onClick={instagram}><Camera className="h-4 w-4"/> Buscar no Instagram</Button></div></Card><Card className="p-6"><h2 className="text-xl font-black">O que observar</h2><ul className="mt-4 space-y-3 text-sm text-muted-foreground"><li>• Os serviços e horários são fáceis de encontrar?</li><li>• O site funciona bem no celular?</li><li>• Existe um caminho claro para contato ou orçamento?</li><li>• As informações coincidem no Maps e nas redes?</li><li>• Que melhoria concreta você pode demonstrar?</li></ul></Card></section><section className="border-y border-border py-7"><h2 className="text-2xl font-black">Prepare o primeiro contato</h2><p className="mt-1 text-sm text-muted-foreground">Registre uma observação real para não enviar uma mensagem genérica.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Empresa<Input className="mt-2" value={company} onChange={e=>setCompany(e.target.value)} placeholder="Nome do negócio"/></label><label className="text-xs font-bold">Onde entrar em contato<Input className="mt-2" value={contact} onChange={e=>setContact(e.target.value)} placeholder="WhatsApp, direct, e-mail..."/></label></div><label className="mt-4 block text-xs font-bold">O que você percebeu<Textarea className="mt-2" value={observation} onChange={e=>setObservation(e.target.value)} placeholder="Ex.: o perfil mostra serviços, mas não tem um link com informações e agendamento"/></label><div className="mt-5 border-l-4 border-primary bg-muted/60 p-5 text-sm leading-7">{message}</div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={async()=>{try{await navigator.clipboard.writeText(message);toast.success('Mensagem copiada!')}catch{toast.error('Não foi possível copiar.')}}}><Copy className="h-4 w-4"/> Copiar mensagem</Button><Link to="/project"><Button variant="outline">Continuar o projeto <ArrowRight className="h-4 w-4"/></Button></Link></div></section></div>}
