import { createFileRoute } from '@tanstack/react-router';
import { useMemo, useState } from 'react';
import { Calculator, Check, Copy, Download, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { formatMoney, nicheAdjustments, pricingExtras, pricingTiers } from '@/lib/pricing-catalog';

export const Route=createFileRoute('/_authenticated/pricing-calculator')({head:()=>({meta:[{title:'Precificação — Prime'},{name:'description',content:'Escolha uma faixa de preço e ajuste ao projeto.'},{property:'og:title',content:'Precificação — Prime'},{property:'og:description',content:'Referências práticas de preço por escopo e nicho.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:PricingCalculatorPage});

function PricingCalculatorPage(){
  const [tierId,setTierId]=useState('intermediate');
  const [nicheId,setNicheId]=useState('local');
  const [extras,setExtras]=useState<string[]>([]);
  const [customAdjustment,setCustomAdjustment]=useState(0);
  const tier=pricingTiers.find(item=>item.id===tierId)??pricingTiers[2];
  const niche=nicheAdjustments.find(item=>item.id===nicheId)??nicheAdjustments[0];
  const result=useMemo(()=>tier.price+niche.amount+pricingExtras.filter(item=>extras.includes(item.id)).reduce((total,item)=>total+item.price,0)+customAdjustment,[tier,niche,extras,customAdjustment]);
  const rangeMin=Math.max(350,Math.round(result*.9/10)*10);
  const rangeMax=Math.round(result*1.15/10)*10;
  const summary=`Proposta de site — ${tier.name}\nPerfil: ${niche.name}\nInclui: ${tier.items.join(', ')}\nAdicionais: ${pricingExtras.filter(item=>extras.includes(item.id)).map(item=>item.name).join(', ')||'Nenhum'}\nInvestimento sugerido: ${formatMoney(result)}\nFaixa para negociação: ${formatMoney(rangeMin)} a ${formatMoney(rangeMax)}`;
  const copy=async()=>{try{await navigator.clipboard.writeText(summary);toast.success('Resumo copiado!')}catch{toast.error('Não foi possível copiar.')}};
  const download=()=>{const url=URL.createObjectURL(new Blob([summary],{type:'text/plain;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='proposta-prime.txt';anchor.click();URL.revokeObjectURL(url)};
  return <div className="mx-auto max-w-6xl space-y-8 pb-20">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-primary">Prime Finance</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Precificação</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Comece por uma referência realista e aumente quando o nicho, o escopo ou a urgência exigirem mais.</p></div><div className="flex gap-2"><Button variant="outline" onClick={copy}><Copy className="h-4 w-4"/> Copiar</Button><Button variant="outline" onClick={download}><Download className="h-4 w-4"/> Baixar</Button></div></div>
    <section><h2 className="mb-4 text-lg font-black">1 · Escolha o nível da entrega</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{pricingTiers.map(item=><Button key={item.id} variant={tierId===item.id?'default':'outline'} className="h-auto min-h-40 flex-col items-start justify-start whitespace-normal p-4 text-left" onClick={()=>setTierId(item.id)}><span className="text-xs opacity-70">{item.name}</span><strong className="mt-2 text-2xl">{formatMoney(item.price)}</strong><span className="mt-2 text-xs font-normal leading-5 opacity-80">{item.description}</span></Button>)}</div></section>
    <div className="grid gap-7 lg:grid-cols-[1fr_350px]"><section className="space-y-7 border-y border-border py-6"><div><h2 className="mb-3 text-lg font-black">2 · Ajuste ao tipo de cliente</h2><Select value={nicheId} onValueChange={setNicheId}><SelectTrigger className="max-w-md"><SelectValue/></SelectTrigger><SelectContent>{nicheAdjustments.map(item=><SelectItem key={item.id} value={item.id}>{item.name}{item.amount?` · + ${formatMoney(item.amount)}`:''}</SelectItem>)}</SelectContent></Select></div><div><h2 className="mb-3 text-lg font-black">3 · Marque o que aumenta o trabalho</h2><div className="grid gap-2 sm:grid-cols-2">{pricingExtras.map(item=><Button key={item.id} variant={extras.includes(item.id)?'default':'outline'} className="h-auto min-h-12 justify-between whitespace-normal" onClick={()=>setExtras(value=>value.includes(item.id)?value.filter(id=>id!==item.id):[...value,item.id])}>{item.name}<span>+ {formatMoney(item.price)}</span></Button>)}</div></div><label className="block max-w-sm text-sm font-bold">Outro ajuste (R$)<Input className="mt-2" type="number" min="0" value={customAdjustment} onChange={event=>setCustomAdjustment(Math.max(0,Number(event.target.value)||0))}/></label><div className="border-l-4 border-primary bg-muted p-4 text-sm"><strong>Quando cobrar mais?</strong><p className="mt-1 text-muted-foreground">Aumente a referência quando houver muitas páginas, produção de texto, catálogo, integrações, prazo curto, várias revisões ou um cliente de maior valor. Explique sempre o que mudou no escopo.</p></div></section>
      <aside className="self-start border border-primary bg-card p-6"><Calculator className="h-6 w-6 text-primary"/><p className="mt-5 text-xs font-black uppercase text-muted-foreground">Preço sugerido</p><p className="mt-2 break-words text-4xl font-black">{formatMoney(result)}</p><p className="mt-2 text-sm text-muted-foreground">Faixa segura: {formatMoney(rangeMin)} a {formatMoney(rangeMax)}</p><div className="mt-6 border-t border-border pt-5"><p className="font-black">{tier.name}</p><p className="mt-1 text-xs text-muted-foreground">Melhor para: {tier.bestFor}</p><ul className="mt-4 space-y-2 text-sm">{tier.items.map(item=><li key={item} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-primary"/>{item}</li>)}</ul></div>{result>tier.price&&<p className="mt-5 flex gap-2 bg-muted p-3 text-xs"><TrendingUp className="h-4 w-4 shrink-0 text-primary"/>O valor subiu porque o perfil ou os adicionais exigem mais trabalho.</p>}</aside></div>
  </div>;
}