import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useMemo, useState } from 'react';
import { Search, Wand2, MessageSquare, Calculator, TrendingUp, ArrowLeft, ArrowRight, Check, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { makeSalesScript, personalizeSales, salesChannels, salesObjectives, salesSituations } from '@/lib/sales-scripts';
import { toast } from 'sonner';

export const Route=createFileRoute('/_authenticated/project')({head:()=>({meta:[{title:'Novo projeto — Prime'},{name:'description',content:'Da prospecção à escala, desenvolva uma venda de site em um fluxo guiado.'},{property:'og:title',content:'Novo projeto — Prime'},{property:'og:description',content:'Prospecção, criação, venda, preço e escala em um único fluxo.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:ProjectPage});

const steps=[{title:'Prospectar',icon:Search},{title:'Criar o site',icon:Wand2},{title:'Conduzir a venda',icon:MessageSquare},{title:'Definir o preço',icon:Calculator},{title:'Escalar',icon:TrendingUp}];
const niches=['Clínica','Odontologia','Estética','Restaurante','Advocacia','Imobiliária','Academia','Arquitetura','Contabilidade','Pet Shop','Outro'];
const objectives=['Gerar contatos','Receber orçamentos','Agendamento','Apresentar serviços','Vender produtos','Outro'];
const packages=[{name:'Entrada',price:350,detail:'Página única e objetiva'},{name:'Simples',price:590,detail:'Site essencial para começar'},{name:'Intermediário',price:750,detail:'Estrutura completa para negócio local'},{name:'Profissional',price:990,detail:'Mais páginas, conteúdo e conversão'},{name:'Premium',price:1450,detail:'Projeto amplo ou nicho de maior valor'}];
const scaleActions=['Pedir uma avaliação após a entrega','Solicitar duas indicações ao cliente','Criar um modelo reutilizável para o nicho','Oferecer manutenção e atualizações','Separar horários fixos para prospecção'];

type ProjectData={name:string;niche:string;customNiche:string;city:string;observation:string;objective:string;customObjective:string;context:string;channel:string;situation:string;salesObjective:string;contact:string;packageIndex:number;scale:string[]};
const initial:ProjectData={name:'',niche:'',customNiche:'',city:'',observation:'',objective:'',customObjective:'',context:'',channel:'',situation:'',salesObjective:'',contact:'',packageIndex:2,scale:[]};

function ProjectPage(){
 const [stage,setStage]=useState(0);const [data,setData]=useState<ProjectData>(initial);const [scriptIndex,setScriptIndex]=useState(0);const [prompt,setPrompt]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('prime-current-project')||'{}');if(saved.data)setData({...initial,...saved.data});if(Number.isInteger(saved.stage)&&saved.stage>=0&&saved.stage<steps.length)setStage(saved.stage)}catch{}},[]);
 const save=(nextData=data,nextStage=stage)=>{setData(nextData);setStage(nextStage);localStorage.setItem('prime-current-project',JSON.stringify({data:nextData,stage:nextStage}))};
 const change=<K extends keyof ProjectData>(key:K,value:ProjectData[K])=>save({...data,[key]:value});
 const finalNiche=data.niche==='Outro'?data.customNiche.trim():data.niche;const finalObjective=data.objective==='Outro'?data.customObjective.trim():data.objective;
 const selectedPackage=packages[data.packageIndex]??packages[0]??{name:'Entrada',price:350,detail:'Página única e objetiva'};
 const scripts=useMemo(()=>data.channel&&data.situation&&data.salesObjective?makeSalesScript(data.channel,data.situation,data.salesObjective):[],[data.channel,data.situation,data.salesObjective]);const currentScript=scripts[scriptIndex];
 const generatedPrompt=`CRIE UM SITE PROFISSIONAL PARA:\nEmpresa: ${data.name||'[empresa]'}\nNicho: ${finalNiche||'[nicho]'}\nCidade: ${data.city||'[cidade]'}\nObjetivo: ${finalObjective||'gerar novos contatos'}\nContexto: ${data.context||data.observation||'[descreva o negócio]'}\n\nCrie uma experiência responsiva e específica para o negócio, com apresentação clara dos serviços, benefícios, provas reais, perguntas frequentes e chamadas para WhatsApp. Não invente dados, resultados ou depoimentos.`;
 const next=()=>{if(stage===0&&(!finalNiche||!data.city.trim())){toast.error('Escolha o nicho e informe a cidade.');return}if(stage===1&&(!data.name.trim()||!data.context.trim())){toast.error('Informe a empresa e o contexto do negócio.');return}if(stage===2&&(!data.channel||!data.situation||!data.salesObjective)){toast.error('Complete as três escolhas do roteiro.');return}if(stage<steps.length-1){save(data,stage+1);toast.success('Etapa concluída!')}else toast.success('Projeto concluído!')};
 const copy=async(text:string,label:string)=>{try{await navigator.clipboard.writeText(text);toast.success(label)}catch{toast.error('Não foi possível copiar.')}};
 return <div className="mx-auto max-w-6xl space-y-7 pb-20"><div><p className="text-xs font-black uppercase text-primary">Prime · Projeto guiado</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Novo projeto</h1><p className="mt-3 max-w-3xl text-sm text-muted-foreground">Faça todas as etapas aqui. Suas informações e seu avanço ficam salvos neste navegador.</p></div>
 <nav className="grid grid-cols-5 gap-1 border-y border-border py-4" aria-label="Etapas do projeto">{steps.map((item,i)=>{const Icon=item.icon;return <Button key={item.title} variant={stage===i?'default':'ghost'} className="h-auto min-w-0 flex-col gap-1 px-1 py-3" onClick={()=>save(data,i)}><Icon className="h-4 w-4 shrink-0"/><span className="hidden truncate text-[10px] sm:block">{i+1}. {item.title}</span><span className="text-[10px] sm:hidden">{i+1}</span></Button>})}</nav>
 <section className="border border-border bg-card p-5 md:p-8">
 {stage===0&&<div className="space-y-6"><div><p className="text-xs font-bold text-primary">ETAPA 1 DE 5</p><h2 className="mt-1 text-2xl font-black">Escolha onde prospectar</h2><p className="mt-2 text-sm text-muted-foreground">Defina um nicho e uma região antes de procurar empresas reais.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Nicho<Select value={data.niche} onValueChange={v=>change('niche',v)}><SelectTrigger className="mt-2"><SelectValue placeholder="Escolha um nicho"/></SelectTrigger><SelectContent>{niches.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{data.niche==='Outro'&&<Input className="mt-2" value={data.customNiche} onChange={e=>change('customNiche',e.target.value)} placeholder="Digite o nicho"/>}</label><label className="text-sm font-bold">Cidade ou região<Input className="mt-2" value={data.city} onChange={e=>change('city',e.target.value)} placeholder="Ex.: Curitiba - PR"/></label><label className="text-sm font-bold">Empresa encontrada<Input className="mt-2" value={data.name} onChange={e=>change('name',e.target.value)} placeholder="Nome do negócio"/></label><label className="text-sm font-bold">Oportunidade observada<Input className="mt-2" value={data.observation} onChange={e=>change('observation',e.target.value)} placeholder="Ex.: não possui site próprio"/></label></div><div className="border-l-4 border-primary bg-muted/60 p-4 text-sm">Pesquise por <strong>{finalNiche||'[nicho]'} em {data.city||'[cidade]'}</strong> no Maps, Instagram ou busca local. Registre acima uma empresa e uma observação real.</div></div>}
 {stage===1&&<div className="space-y-6"><div><p className="text-xs font-bold text-primary">ETAPA 2 DE 5</p><h2 className="mt-1 text-2xl font-black">Prepare o site</h2><p className="mt-2 text-sm text-muted-foreground">O nicho e a empresa da etapa anterior já acompanham o projeto.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Empresa<Input className="mt-2" value={data.name} onChange={e=>change('name',e.target.value)} placeholder="Nome da empresa"/></label><label className="text-sm font-bold">Objetivo<Select value={data.objective} onValueChange={v=>change('objective',v)}><SelectTrigger className="mt-2"><SelectValue placeholder="Escolha um objetivo"/></SelectTrigger><SelectContent>{objectives.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{data.objective==='Outro'&&<Input className="mt-2" value={data.customObjective} onChange={e=>change('customObjective',e.target.value)} placeholder="Digite o objetivo"/>}</label></div><label className="block text-sm font-bold">Contexto do negócio<Textarea className="mt-2 min-h-36" value={data.context} onChange={e=>change('context',e.target.value)} placeholder="Serviços, público, diferenciais, oferta e informações reais do negócio"/></label><Button onClick={()=>{setPrompt(generatedPrompt);toast.success('Briefing gerado!')}}><Wand2 className="h-4 w-4"/> Gerar briefing</Button>{prompt&&<div className="space-y-3 border-l-4 border-primary bg-muted/60 p-5"><pre className="whitespace-pre-wrap text-sm leading-6">{prompt}</pre><Button variant="outline" onClick={()=>void copy(prompt,'Briefing copiado!')}><Copy className="h-4 w-4"/> Copiar briefing</Button></div>}</div>}
 {stage===2&&<div className="space-y-6"><div><p className="text-xs font-bold text-primary">ETAPA 3 DE 5</p><h2 className="mt-1 text-2xl font-black">Conduza a conversa</h2><p className="mt-2 text-sm text-muted-foreground">Escolha o canal, o cenário e seu objetivo. Depois avance por todo o roteiro.</p></div><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Canal<Select value={data.channel} onValueChange={v=>{change('channel',v);setScriptIndex(0)}}><SelectTrigger className="mt-2"><SelectValue placeholder="Escolha"/></SelectTrigger><SelectContent>{salesChannels.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></label><label className="text-sm font-bold">Situação<Select value={data.situation} onValueChange={v=>{change('situation',v);setScriptIndex(0)}}><SelectTrigger className="mt-2"><SelectValue placeholder="Escolha"/></SelectTrigger><SelectContent>{salesSituations.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></label><label className="text-sm font-bold">Objetivo da conversa<Select value={data.salesObjective} onValueChange={v=>{change('salesObjective',v);setScriptIndex(0)}}><SelectTrigger className="mt-2"><SelectValue placeholder="Escolha"/></SelectTrigger><SelectContent>{salesObjectives.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></label></div><label className="block text-sm font-bold">Nome do contato<Input className="mt-2 max-w-sm" value={data.contact} onChange={e=>change('contact',e.target.value)} placeholder="Nome da pessoa"/></label>{currentScript&&<div className="border border-primary/40 p-5 md:p-7"><p className="text-xs font-black text-primary">PARTE {scriptIndex+1} DE {scripts.length}</p><h3 className="mt-2 text-xl font-black">{currentScript.title}</h3><p className="mt-1 text-sm text-muted-foreground">{currentScript.purpose}</p><div className="mt-5 border-l-4 border-primary bg-muted/60 p-4 text-sm leading-7">{personalizeSales(currentScript.text,{person:data.contact,company:data.name,seller:'[Seu Nome]',detail:data.observation})}</div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>void copy(personalizeSales(currentScript.text,{person:data.contact,company:data.name,seller:'[Seu Nome]',detail:data.observation}),'Etapa copiada!')}><Copy className="h-4 w-4"/> Copiar</Button><Button variant="outline" disabled={scriptIndex===0} onClick={()=>setScriptIndex(i=>i-1)}><ArrowLeft className="h-4 w-4"/> Anterior</Button><Button variant="outline" disabled={scriptIndex===scripts.length-1} onClick={()=>setScriptIndex(i=>i+1)}>Próxima <ArrowRight className="h-4 w-4"/></Button></div></div>}</div>}
 {stage===3&&<div className="space-y-6"><div><p className="text-xs font-bold text-primary">ETAPA 4 DE 5</p><h2 className="mt-1 text-2xl font-black">Defina o preço</h2><p className="mt-2 text-sm text-muted-foreground">Escolha uma faixa compatível com o escopo e a realidade do cliente.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{packages.map((item,i)=><Button key={item.price} variant={data.packageIndex===i?'default':'outline'} className="h-auto min-h-28 flex-col items-start whitespace-normal p-4 text-left" onClick={()=>change('packageIndex',i)}><span className="text-xs">{item.name}</span><strong className="text-xl">R$ {item.price}</strong><span className="text-[10px] opacity-70">{item.detail}</span></Button>)}</div><div className="border-l-4 border-primary bg-muted/60 p-5"><strong>Valor sugerido: R$ {selectedPackage.price}</strong><p className="mt-2 text-sm text-muted-foreground">Saúde, advocacia, imóveis e projetos com catálogo, agendamento ou muitas páginas podem justificar uma faixa maior. Aumente preço junto com escopo, valor e complexidade.</p></div></div>}
 {stage===4&&<div className="space-y-6"><div><p className="text-xs font-bold text-primary">ETAPA 5 DE 5</p><h2 className="mt-1 text-2xl font-black">Prepare a escala</h2><p className="mt-2 text-sm text-muted-foreground">Transforme cada entrega em processo, recorrência e novas oportunidades.</p></div><div className="grid gap-3 sm:grid-cols-2">{scaleActions.map(action=><Button key={action} variant={data.scale.includes(action)?'default':'outline'} className="h-auto min-h-14 justify-start whitespace-normal text-left" onClick={()=>change('scale',data.scale.includes(action)?data.scale.filter(x=>x!==action):[...data.scale,action])}>{data.scale.includes(action)&&<Check className="h-4 w-4 shrink-0"/>}{action}</Button>)}</div><div className="border-l-4 border-primary bg-muted/60 p-5 text-sm leading-6">Comece repetindo o mesmo nicho, documente seu processo e use cada projeto concluído como prova real. Escala vem de consistência, indicação e uma oferta simples de explicar.</div></div>}
 <div className="mt-8 flex flex-wrap justify-between gap-3 border-t border-border pt-5"><Button variant="outline" disabled={stage===0} onClick={()=>save(data,stage-1)}><ArrowLeft className="h-4 w-4"/> Etapa anterior</Button><Button onClick={next}>{stage===steps.length-1?'Concluir projeto':'Confirmar e avançar'} <ArrowRight className="h-4 w-4"/></Button></div>
 </section></div>;
}