import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Calculator, Pencil, Plus, Search, Target, Wand2, MessageSquare, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Painel — Prime"},{name:"description",content:"Organize suas metas e seus projetos de sites."},{property:"og:title",content:"Painel — Prime"},{property:"og:description",content:"Organize suas metas e seus projetos de sites."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:DashboardPage});
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
const links=[{title:'Radar de Clientes',description:'Encontre uma empresa',to:'/prospecting' as const,icon:Search},{title:'Criador de Sites',description:'Prepare o site',to:'/ai-builder' as const,icon:Wand2},{title:'Scripts de Venda',description:'Conduza a conversa',to:'/scripts' as const,icon:MessageSquare},{title:'Precificação',description:'Monte o preço',to:'/pricing-calculator' as const,icon:Calculator}];
function DashboardPage(){
  const [goal,setGoal]=useState(7500);const [revenue,setRevenue]=useState(0);const [editing,setEditing]=useState(false);const [draftGoal,setDraftGoal]=useState('7500');const [draftRevenue,setDraftRevenue]=useState('0');
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('prime-goals')||'{}');if(typeof saved.goal==='number'&&saved.goal>0){setGoal(saved.goal);setDraftGoal(String(saved.goal))}if(typeof saved.revenue==='number'&&saved.revenue>=0){setRevenue(saved.revenue);setDraftRevenue(String(saved.revenue))}}catch{ /* Ignore outdated local data. */ }},[]);
  const save=()=>{const nextGoal=Number(draftGoal),nextRevenue=Number(draftRevenue);if(!Number.isFinite(nextGoal)||nextGoal<=0||!Number.isFinite(nextRevenue)||nextRevenue<0){toast.error('Informe valores válidos para a meta e o faturamento.');return}setGoal(nextGoal);setRevenue(nextRevenue);localStorage.setItem('prime-goals',JSON.stringify({goal:nextGoal,revenue:nextRevenue}));setEditing(false);toast.success('Meta atualizada')};
  const progress=Math.min(100,Math.round(revenue/goal*100));
  return <div className="mx-auto max-w-6xl space-y-8 pb-20 text-foreground">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase text-muted-foreground">Seu espaço de trabalho</p><h1 className="mt-2 text-4xl font-black md:text-5xl">Vamos vender mais sites.</h1><p className="mt-3 text-sm text-muted-foreground">Do primeiro contato à entrega, organize cada passo em um só lugar.</p></div><Link to="/project"><Button className="h-11 font-bold"><Plus className="h-4 w-4"/> Novo projeto</Button></Link></div>
    <section className="border border-border bg-card p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black uppercase text-muted-foreground"><Target className="h-4 w-4 text-primary"/> Meta de faturamento</p><p className="mt-3 text-4xl font-black">{money(goal)}</p><p className="mt-2 text-sm text-muted-foreground">{money(revenue)} registrado · {money(Math.max(0,goal-revenue))} para alcançar a meta</p></div><Button variant="outline" onClick={()=>setEditing(v=>!v)}><Pencil className="h-4 w-4"/> {editing?'Cancelar':'Editar meta'}</Button></div><div className="mt-6 h-3 overflow-hidden bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs font-semibold text-muted-foreground">{progress}% da meta</p>{editing&&<div className="mt-6 grid gap-3 border-t border-border pt-5 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-sm font-semibold">Meta (R$)<Input type="number" min="1" step="50" value={draftGoal} onChange={e=>setDraftGoal(e.target.value)} className="mt-2"/></label><label className="text-sm font-semibold">Faturado (R$)<Input type="number" min="0" step="50" value={draftRevenue} onChange={e=>setDraftRevenue(e.target.value)} className="mt-2"/></label><Button onClick={save}>Salvar meta</Button></div>}</section>
    <section><div className="mb-4"><h2 className="text-2xl font-black">Seu próximo projeto</h2><p className="text-sm text-muted-foreground">Comece pelo Radar e avance até o preço e a escala.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{links.map((item,i)=>{const Icon=item.icon;return <Link to={item.to} key={item.to}><Card className="h-full p-5 transition hover:border-primary"><div className="flex items-center justify-between"><span className="text-xs font-black text-muted-foreground">0{i+1}</span><Icon className="h-5 w-5 text-primary"/></div><h3 className="mt-7 text-base font-black">{item.title}</h3><p className="mt-1 text-xs text-muted-foreground">{item.description}</p></Card></Link>})}</div><Link to="/project"><Button variant="outline" className="mt-5">Abrir fluxo completo <ArrowRight className="h-4 w-4"/></Button></Link></section>
  </div>;
}
