import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Wand2, Copy, Sparkles, Target, Palette, LayoutTemplate } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/ai-builder")({ head:()=>({meta:[{title:"Criador de Sites — Prime"},{name:"description",content:"Gere briefings detalhados para sites empresariais."},{property:"og:title",content:"Criador de Sites — Prime"},{property:"og:description",content:"Transforme contexto de negócio em um projeto profissional."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: AIBuilderPage });

function AIBuilderPage() {
  const [loading,setLoading]=useState(false); const [result,setResult]=useState<string|null>(null);
  const [context,setContext]=useState(""); const [niche,setNiche]=useState(""); const [customNiche,setCustomNiche]=useState("");
  const [companyName,setCompanyName]=useState(""); const [city,setCity]=useState(""); const [objective,setObjective]=useState(""); const [customObjective,setCustomObjective]=useState("");
  const [style,setStyle]=useState(""); const [colors,setColors]=useState(""); const [targetAudience,setTargetAudience]=useState(""); const [mainBenefit,setMainBenefit]=useState(""); const [toneVoice,setToneVoice]=useState("");
  const niches=['Digitar meu nicho','Clínica Médica','Odontologia','Estética','Restaurante','Advocacia','Imobiliária','Academia','Arquitetura','Consultoria','Educação','Eventos','Pet Shop','E-commerce','SaaS / Tecnologia','Construção','Contabilidade','Hotelaria','Fotografia'];
  const objectives=['Digitar meu objetivo','Gerar leads','Agendamento','Vender produtos','Vender serviços','Apresentar portfólio','Gerar autoridade','Capturar WhatsApp','Receber orçamentos'];
  const styles=['Premium / Luxuoso','Minimalista','Moderno','Corporativo','Criativo','Elegante','Tecnológico','Clean'];
  const tones=['Profissional','Persuasivo','Humano','Autoridade','Premium','Descontraído'];
  const finalNiche=niche==='Digitar meu nicho'?customNiche.trim():niche; const finalObjective=objective==='Digitar meu objetivo'?customObjective.trim():objective;
  const handleGenerate=()=>{if(!companyName||!finalNiche||!context){toast.error('Informe empresa, nicho e contexto do negócio.');return;} setLoading(true); setTimeout(()=>{const prompt=`CRIE UM SITE PROFISSIONAL E PERSONALIZADO PARA:\nEmpresa: ${companyName}\nNicho: ${finalNiche}\nCidade: ${city||'Brasil'}\nObjetivo principal: ${finalObjective||'Conversão'}\nPúblico: ${targetAudience||'Clientes em potencial'}\nDiferencial: ${mainBenefit||'Definir a partir do contexto'}\nContexto real: ${context}\nEstilo: ${style||'Moderno e premium'}\nTom: ${toneVoice||'Profissional'}\nCores: ${colors||'Definir uma paleta coerente'}\n\nDIREÇÃO: não use template genérico. Cruze nicho, público e objetivo para definir arquitetura, copy, imagens, tipografia, componentes e jornada. Crie uma primeira dobra forte, navegação intuitiva, seções de confiança, serviços, benefícios, prova social, FAQ e CTA final. Use imagens relevantes e carrosséis quando ajudarem. Todos os elementos devem ser responsivos, acessíveis e visualmente consistentes.\n\nCONVERSÃO: conduza ATENÇÃO → INTERESSE → CONFIANÇA → DESEJO → AÇÃO. Use CTAs estratégicos e copy específica. Inclua CTA principal de WhatsApp nas áreas de maior intenção e nunca invente informações ou depoimentos.\n\nENTREGA: gere uma experiência premium, moderna e memorável, com espaçamento refinado, microinterações, estados de hover, boa hierarquia visual e excelente versão mobile.`; setResult(prompt);setLoading(false);toast.success('Prompt profissional gerado!');},700)};
  return <div className="max-w-6xl mx-auto space-y-8 pb-20">
    <div><div className="flex items-center gap-2 text-[#8A6A00] text-[10px] font-black uppercase tracking-[.2em]"><Sparkles className="h-4 w-4 text-[#FFD600]"/> Prime AI Builder</div><h1 className="text-4xl md:text-5xl font-black tracking-tighter mt-2">Crie sites que parecem feitos sob medida.</h1><p className="text-muted-foreground mt-3 max-w-2xl">Defina o negócio, objetivo e direção criativa. A Prime transforma isso em um briefing pronto para gerar um site profissional.</p></div>
    <div className="grid lg:grid-cols-[1fr_300px] gap-6">
      <div className="rounded-3xl border border-[#E4E7E1] bg-card p-6 md:p-8 space-y-7 shadow-sm">
        <div className="grid md:grid-cols-2 gap-5">
          <div className="space-y-2"><Label>Nicho do cliente</Label><Select value={niche} onValueChange={setNiche}><SelectTrigger><SelectValue placeholder="Escolha ou digite um nicho"/></SelectTrigger><SelectContent>{niches.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{niche==='Digitar meu nicho'&&<Input className="mt-2" autoFocus value={customNiche} onChange={e=>setCustomNiche(e.target.value)} placeholder="Escreva o nicho do cliente"/>}</div>
          <div className="space-y-2"><Label>Nome da empresa</Label><Input value={companyName} onChange={e=>setCompanyName(e.target.value)} placeholder="Ex.: Clínica Prime"/></div>
          <div className="space-y-2"><Label>Cidade / região</Label><Input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: São Paulo - SP"/></div>
          <div className="space-y-2"><Label>Objetivo do site</Label><Select value={objective} onValueChange={setObjective}><SelectTrigger><SelectValue placeholder="Escolha ou digite um objetivo"/></SelectTrigger><SelectContent>{objectives.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{objective==='Digitar meu objetivo'&&<Input className="mt-2" autoFocus value={customObjective} onChange={e=>setCustomObjective(e.target.value)} placeholder="Escreva o objetivo do site"/>}</div>
        </div>
        <div className="grid md:grid-cols-2 gap-5"><div className="space-y-2"><Label>Público-alvo</Label><Input value={targetAudience} onChange={e=>setTargetAudience(e.target.value)} placeholder="Quem precisa ser convencido?"/></div><div className="space-y-2"><Label>Diferencial / oferta</Label><Input value={mainBenefit} onChange={e=>setMainBenefit(e.target.value)} placeholder="O que torna o negócio diferente?"/></div></div>
        <div className="rounded-2xl border-2 border-[#FFD600]/50 bg-[#FFFBE6] dark:bg-[#2a2608] p-5 space-y-3"><div className="flex items-center gap-2"><Target className="h-5 w-5 text-[#FFD600]"/><Label className="text-base font-black">Briefing do negócio</Label></div><Textarea value={context} onChange={e=>setContext(e.target.value)} className="min-h-[170px] bg-white dark:bg-[#11130f]" placeholder="Explique serviços, público, problema que resolve, diferenciais, provas, localização, oferta e tudo que a IA precisa saber. Você pode escrever livremente."/><p className="text-xs text-[#6f6846] dark:text-[#d9d4a8]">Quanto melhor o briefing, mais personalizado será o resultado. Não precisa escrever de forma técnica.</p></div>
        <div className="grid md:grid-cols-3 gap-5"><div className="space-y-2"><Label>Estilo visual</Label><Select value={style} onValueChange={setStyle}><SelectTrigger><SelectValue placeholder="Escolha"/></SelectTrigger><SelectContent>{styles.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Tom de voz</Label><Select value={toneVoice} onValueChange={setToneVoice}><SelectTrigger><SelectValue placeholder="Escolha"/></SelectTrigger><SelectContent>{tones.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Cores</Label><Input value={colors} onChange={e=>setColors(e.target.value)} placeholder="Ex.: preto, dourado e branco"/></div></div>
        <Button onClick={handleGenerate} disabled={loading} className="w-full h-14 bg-[#FFD600] hover:bg-[#FFDF00] text-[#111] font-black uppercase tracking-wider">{loading?'Montando briefing...':<>Gerar Prompt Profissional <Wand2 className="ml-2 h-5 w-5"/></>}</Button>
      </div>
      <div className="space-y-4"><div className="rounded-3xl border border-border bg-card p-5"><Palette className="h-6 w-6 text-[#FFD600]"/><p className="font-black mt-4">Direção visual</p><p className="text-xs text-muted-foreground mt-1">A identidade escolhida guia cores, imagens, componentes e ritmo da página.</p></div><div className="rounded-3xl border border-border bg-card p-5"><LayoutTemplate className="h-6 w-6 text-[#FFD600]"/><p className="font-black mt-4">Estrutura inteligente</p><p className="text-xs text-muted-foreground mt-1">A Prime prioriza as seções que fazem sentido para o objetivo do projeto.</p></div></div>
    </div>
    {result&&<div className="rounded-3xl border-2 border-[#FFD600] bg-card p-6 space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#8A6A00]">Resultado</p><h2 className="text-xl font-black">Prompt pronto para usar</h2></div><Button onClick={()=>{navigator.clipboard.writeText(result);toast.success('Prompt copiado!')}} className="bg-[#FFD600] text-[#111] hover:bg-[#FFDF00]"><Copy className="mr-2 h-4 w-4"/> Copiar prompt</Button></div><pre className="whitespace-pre-wrap rounded-2xl border border-border bg-background p-5 text-sm leading-6 max-h-[520px] overflow-auto">{result}</pre></div>}
  </div>;
}