import "../landing.css";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, Check, ChevronDown, MapPin, Moon, Search, Sparkles, Sun, Zap } from "lucide-react";

export const Route = createFileRoute("/")({
  component: LandingPage,
  head: () => ({
    title: "Valy OS — Venda sites para o comércio da sua cidade",
    meta: [
      { name: "description", content: "Ache negócios sem site, gere páginas profissionais e transforme oportunidades locais em vendas." },
      { property: "og:title", content: "Venda sites para o comércio da sua cidade" },
      { property: "og:description", content: "Da prospecção ao fechamento em um único lugar." },
    ],
  }),
});

const painPoints = [
  "Passa horas montando cada site à mão",
  "Cobra pouco porque o site demora a sair",
  "Não sabe onde encontrar quem precisa de site",
  "Perde o cliente entre o orçamento e a entrega",
  "Manda proposta sem contrato e sem preço definido",
  "Depende de designer ou programador para entregar",
];
const tools = [
  ["01", "Prospecção", "Busca no Google Maps os negócios da sua cidade que ainda não têm site, com telefone e endereço.", Search],
  ["02", "Gerador de sites", "Responde um questionário guiado e o site sai pronto em menos de 1 minuto, com as fotos do negócio.", Sparkles],
  ["03", "Editor visual", "Ajusta textos, cores, fotos e seções no clique, sem código, quantas vezes precisar.", Zap],
  ["04", "CRM e fechamento", "Script de abordagem, precificação, contrato e o funil de cada cliente até a entrega.", MapPin],
];
const steps = [
  ["01", "Ative sua conta", "Assine, acesse a plataforma e configure sua operação. Em poucos cliques você já está pronto para começar."],
  ["02", "Monte o projeto", "Responda um questionário rápido sobre o negócio e o site sai pronto em menos de 1 minuto, dentro da plataforma."],
  ["03", "Encontre clientes", "Use a busca por região pra achar negócios que ainda não têm site e aborde centenas por dia, cada um com o site dele já pronto na mão."],
  ["04", "Feche e escale", "Apresente, gere o contrato e receba. Acompanhe tudo no painel e repita o processo."],
];
const faqs = [
  ["Preciso saber programar ou ter experiência com design?", "Não. A plataforma foi feita pra quem está começando: você responde um questionário guiado e ajusta o resultado por uma interface visual, sem escrever código."],
  ["O resultado tem qualidade profissional?", "Sim. Os projetos partem de layouts construídos por designers, com tipografia, espaçamento e responsividade já resolvidos — o que muda é o conteúdo e a identidade de cada cliente."],
  ["Quanto consigo cobrar por projeto?", "Depende do escopo, do nicho e da região. A ferramenta de precificação te ajuda a chegar num valor de mercado com base nessas variáveis, em vez de você chutar."],
  ["Como encontro clientes se não tenho carteira de contatos?", "A busca por região lista negócios da sua cidade que ainda não têm presença online, com nome, telefone e endereço, para você abordar com uma oferta pronta."],
];
function Logo(){return <Link to="/" className="valy-logo" aria-label="Valy"><span className="logo-mark"><i/></span><strong>VALY</strong></Link>}
function LandingPage(){
 const [dark,setDark]=useState(false); const [faq,setFaq]=useState<number|null>(null);
 useEffect(()=>{document.documentElement.classList.toggle("valy-dark",dark);return()=>document.documentElement.classList.remove("valy-dark")},[dark]);
 return <div className="valy-page" id="inicio">
  <div className="valy-grid-bg"/><header className="valy-header"><div className="valy-container valy-nav"><Logo/><nav><a href="#planos">PLANOS</a><a href="#faq">FAQ</a></nav><div className="nav-actions"><button className="theme-btn" aria-label="Alternar tema" onClick={()=>setDark(v=>!v)}>{dark?<Sun/>:<Moon/>}</button><Link className="login-link" to="/auth">ENTRAR</Link><a className="green-btn small" href="#planos">VER PLANOS</a></div></div></header>
  <main>
   <section className="hero valy-container"><div className="hero-badge"><span>✦</span> Sem saber programar · 7 dias de garantia</div><h1>Venda sites para o comércio<br/><em>da sua cidade</em></h1><p className="hero-copy">A Valy OS acha os negócios sem site no Google Maps, monta a abordagem e gera o site pronto em menos de 1 minuto. Você cobra de R$ 500 a R$ 2.000 por projeto — sem saber programar e sem equipe.</p><div className="hero-actions"><a className="green-btn hero-btn" href="#planos">Ver planos e começar a vender <span>→</span></a><Link className="test-link" to="/auth">Prefere testar antes? Crie a conta grátis</Link></div><div className="hero-benefits"><span><Check/> A partir de R$ 74,27/mês</span><span><Check/> 7 dias de garantia</span><span><Check/> Sem instalar nada</span><span><Check/> Site pronto em minutos</span></div><div className="hero-screen"><div className="browser-bar"><b/><b/><b/><span>valy.app / projeto</span></div><div className="screen-inner"><div className="screen-side"><span>VALY</span><i/><i/><i/><i/></div><div className="screen-main"><div className="screen-label">SITE PRONTO</div><strong>Seu próximo cliente já pode conhecer o negócio.</strong><div className="screen-cards"><div/><div/><div/></div></div></div></div></section>
   <div className="industry-strip"><div className="marquee">{["Barbearia","Pizzaria","Clínica","Academia","Advocacia","Estética","Restaurante","Nutrição","Imobiliária","Seguros","Energia solar","Veterinária","Barbearia","Pizzaria","Clínica","Academia","Advocacia","Estética"].map((x,i)=><span key={i}>{x} <b>✦</b></span>)}</div></div>
   <section className="section light" id="dor"><div className="valy-container narrow"><div className="eyebrow">RECONHECE?</div><h2>Você está deixando dinheiro na mesa <em>se:</em></h2><p className="section-intro">Cada item da lista é um site que alguém da sua cidade precisava e você não vendeu.</p><div className="pain-list">{painPoints.map((p,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p><Check/></div>)}</div><div className="solution-callout"><strong>Com a Valy, o site fica pronto em menos de 1 minuto</strong><p>Você entrega com contrato, preço e abordagem prontos. A venda continua sendo sua, mas o trabalho pesado não.</p><a className="green-btn" href="#ferramentas">Quero vender sites <ArrowRight/></a></div></div></section>
   <section className="section" id="ferramentas"><div className="valy-container"><div className="eyebrow">DA BUSCA AO SITE NO AR</div><h2>4 ferramentas. 1 painel.<br/><em>Nenhuma aba perdida.</em></h2><p className="section-intro">Você não precisa de mais nada: a Valy acha o cliente, gera o site, deixa você editar e acompanha a venda no mesmo lugar.</p><div className="tools-grid">{tools.map(([num,title,desc,Icon])=>{const I=Icon as any;return <article className="tool-card" key={title as string}><span className="tool-number">{num as string}</span><div className="tool-icon"><I/></div><h3>{title as string}</h3><p>{desc as string}</p><a href="#planos">Ver como funciona <ArrowRight/></a></article>})}</div></div></section>
   <section className="section soft" id="por-dentro"><div className="valy-container"><div className="eyebrow">POR DENTRO</div><h2>Olha o que você vai ter<br/><em>dentro da Valy</em></h2><p className="section-intro">Telas reais da plataforma, não ilustração. É o que você abre no primeiro dia.</p><div className="dashboard-showcase"><div className="dash-nav"><strong>VALY</strong><span>Dashboard</span><span>Prospecção</span><span>Precificação</span><span>CRM</span></div><div className="dash-content"><div className="dash-top"><div><small>RECEITA</small><strong>R$ 12.480</strong></div><div><small>TICKET MÉDIO</small><strong>R$ 1.560</strong></div><div><small>LEADS</small><strong>48</strong></div></div><div className="dash-body"><div className="chart"><small>FUNIL DE PROSPECÇÃO</small><div className="bars"><i/><i/><i/><i/><i/></div></div><div className="lead-table"><small>OPORTUNIDADES</small><p>Barbearia Central <b>Sem site</b></p><p>Clínica Vida <b>Sem site</b></p><p>Studio Bella <b>Sem site</b></p></div></div></div></div><div className="feature-row"><div><b>Prospecção</b><span>Quem precisa de site, com telefone</span></div><div><b>Precificação</b><span>Quanto cobrar por ramo e tamanho</span></div><div><b>Abordagem</b><span>Script com nome do negócio</span></div><div><b>CRM</b><span>Roteiro e objeções por lead</span></div></div></div></section>
   <section className="section demo"><div className="valy-container"><div className="eyebrow">POR DENTRO, SEM CORTE</div><h2>Como funciona a <em>ferramenta</em></h2><p className="section-intro">A gravação completa da tela: achar o negócio que ainda não tem site, gerar a página, editar e mandar para o cliente.</p><div className="video-placeholder"><div className="play">▶</div><span>DEMONSTRAÇÃO DA PLATAFORMA</span></div><a className="green-btn" href="#planos">Assistir a demonstração <ArrowRight/></a></div></section>
   <section className="section light" id="planos"><div className="valy-container"><div className="eyebrow">PLANOS</div><h2>Escolha como quer começar<br/><em>e comece hoje</em></h2><p className="section-intro">Um site vendido a R$ 500 paga dois meses de plano. Dois sites pagam o ano inteiro.</p><div className="pricing"><article><span className="plan-tag">GRATUITO</span><h3>Para conhecer a Valy</h3><strong>R$ 0</strong><small>Para sempre, sem cartão</small><ul><li>Site completo gerado por IA em 30 segundos</li><li>Até 40 negócios sem site por mês</li><li>Busca em 3 cidades de cada estado</li><li>5 categorias de negócio</li><li>2 sites e 3 edições por mês</li></ul><Link className="outline-btn" to="/auth">Começar grátis</Link></article><article className="featured"><span className="plan-tag">STARTER · MAIS ESCOLHIDO</span><h3>Para começar a vender sites</h3><strong>12 x R$ 74,27</strong><small>ou R$ 697 à vista no Pix</small><ul><li>Sites ilimitados: gere e edite quantos quiser</li><li>Qualquer cidade do Brasil</li><li>17 categorias de negócio</li><li>Sites sem o selo da Valy</li><li>CRM e recursos para fechar clientes</li></ul><a className="green-btn" href="#final">Escolher Starter <ArrowRight/></a></article><article><span className="plan-tag">PRO</span><h3>Para quem quer escalar</h3><strong>12 x R$ 149,27</strong><small>Estrutura completa para operação</small><ul><li>Todos os recursos do Starter</li><li>Mais capacidade de prospecção</li><li>Operação pensada para volume</li><li>Prioridade e recursos avançados</li><li>Mais controle da sua produção</li></ul><a className="outline-btn" href="#final">Ver plano Pro</a></article></div></div></section>
   <section className="section" id="modelos"><div className="valy-container"><div className="eyebrow">O QUE VOCÊ ENTREGA</div><h2>Modelos feitos à mão<br/><em>por designers</em></h2><p className="section-intro">Cada ramo tem um layout próprio, com tipografia, espaçamento e celular já resolvidos. O que muda é o conteúdo e a identidade de cada cliente.</p><div className="model-strip"><div className="model-card pink"><span>Corretora de seguros</span><strong>Proteção para o que importa.</strong></div><div className="model-card green"><span>Clínica</span><strong>Cuidado que começa no primeiro contato.</strong></div><div className="model-card blue"><span>Restaurante</span><strong>Uma experiência que dá vontade de voltar.</strong></div></div></div></section>
   <section className="section soft" id="etapas"><div className="valy-container"><div className="eyebrow">COMO FUNCIONA</div><h2>O caminho mais curto<br/><em>até o primeiro cliente</em></h2><p className="section-intro">Da ativação ao fechamento, numa sequência simples e repetível.</p><div className="steps">{steps.map(([n,t,d])=><article key={n as string}><span>{n as string}</span><div><h3>{t as string}</h3><p>{d as string}</p></div></article>)}</div><a className="green-btn" href="#planos">Escolher meu plano <ArrowRight/></a></div></section>
   <section className="section light"><div className="valy-container narrow"><div className="eyebrow">ANTES DE ESCOLHER UM PLANO</div><h2>A Valy é para <em>você se…</em></h2><p className="section-intro">Sem promessa vazia: a ferramenta encurta o caminho, mas a venda continua sendo sua.</p><div className="fit-grid"><div><h3>Faz sentido se</h3><p>✓ Quer uma renda extra ou um negócio próprio sem saber programar</p><p>✓ Topa falar com donos de comércio pelo WhatsApp ou pessoalmente</p><p>✓ Tem 1 hora por dia para prospectar e apresentar sites</p><p>✓ Já é freelancer ou tem uma agência pequena e quer entregar mais rápido</p></div><div><h3>Não faz sentido se</h3><p>× Espera resultado sem procurar nem abordar nenhum cliente</p><p>× Quer um site para o seu próprio negócio, e só isso</p><p>× Precisa de um sistema com lojas virtuais e carrinho de compras</p></div></div></div></section>
   <section className="section faq-section" id="faq"><div className="valy-container narrow"><div className="eyebrow">PERGUNTAS FREQUENTES</div><h2>Se ficou alguma dúvida,<br/><em>fale com a gente.</em></h2><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-item ${faq===i?"open":""}`} key={q as string}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q as string}</span><ChevronDown/></button>{faq===i&&<p>{a as string}</p>}</div>)}</div></div></section>
   <section className="final-cta" id="final"><div className="valy-container"><div className="final-glow"/><div className="eyebrow">COMECE PELO PRIMEIRO</div><h2>Sua cidade tem negócios<br/>sem site. <em>Comece pelo primeiro.</em></h2><p>Escolha o plano, gere o primeiro site e entregue ainda hoje. Um projeto vendido já paga o ano inteiro.</p><div className="final-actions"><a className="green-btn hero-btn" href="#planos">Escolher meu plano <ArrowRight/></a><Link className="test-link" to="/auth">Quer testar antes? Crie a conta grátis</Link></div><div className="final-benefits"><span>✓ Hospedagem e SSL inclusos</span><span>✓ Botão de WhatsApp no site</span><span>✓ Funciona no celular</span></div></div></section>
  </main>
  <footer className="valy-footer"><div className="valy-container footer-grid"><div><Logo/><p>Sites prontos. Clientes encontrados. Venda local.</p></div><div><b>PLATAFORMA</b><a href="#ferramentas">Ferramentas</a><a href="#planos">Planos</a><a href="#faq">FAQ</a></div><div><b>EMPRESA</b><a href="#etapas">Como funciona</a><a href="#modelos">Modelos</a><a href="#final">Começar</a></div><div><b>LEGAL</b><a href="#">Termos</a><a href="#">Privacidade</a><a href="#">Cookies</a></div></div><div className="footer-bottom valy-container"><span>© 2026 Valy. Todos os direitos reservados.</span><span>Feito para quem quer vender sites.</span></div></footer>
 </div>
}
